create or replace package uc_ai_test_samples as

  -- GENERATED by scripts/generate_test_samples.sh from test/samples/**/*.json.
  -- Do not edit: change the JSON file and run the script (or `make generate`).
  --
  -- Recorded provider requests and responses. p_name is the path below
  -- test/samples without the .json suffix, e.g.
  -- 'openai/chat/4-structured-output-request'. An unknown name raises -20990.

  function get(p_name in varchar2) return clob;

  function get_json(p_name in varchar2) return json_object_t;

end uc_ai_test_samples;
/
