-- ============================================================================
-- UC AI tutorial — "Extract structured data from a PDF"
-- Demo schema: the supplier-invoice inbox
-- ============================================================================
-- Creates five tables and seeds the purchase orders. Safe to run more than one
-- time: it deletes the objects first, so a second run gives the same result as
-- the first.
--
-- The four PDFs go in with 00_load_pdfs.sql, which you run next.
--
-- To remove everything again, run 00_teardown.sql.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.

set define off
set serveroutput on

-- ---------------------------------------------------------------------------
-- Delete the objects of an earlier run
-- ---------------------------------------------------------------------------
declare
  -- Child tables first, so no foreign key blocks a drop.
  c_tables constant sys.odcivarchar2list := sys.odcivarchar2list(
    'INV_INVOICE_LINES'
  , 'INV_INVOICES'
  , 'INV_EXTRACTIONS'
  , 'INV_DOCUMENTS'
  , 'INV_PURCHASE_ORDERS'
  );
  e_table_missing exception;
  pragma exception_init(e_table_missing, -942);
begin
  <<table_loop>>
  for i in 1 .. c_tables.count loop
    begin
      -- @dblinter ignore(g-6010): the name comes from the constant list above, not from user input
      execute immediate 'drop table ' || c_tables(i) || ' cascade constraints purge';
    exception
      when e_table_missing then
        -- @dblinter ignore(g-5080): an absent table is the normal case on a first run
        null;
    end;
  end loop table_loop;
end;
/

-- ---------------------------------------------------------------------------
-- The inbox: one row for each document that arrives
-- ---------------------------------------------------------------------------
-- In production a row lands here from an APEX file upload, a mail interface, or
-- a scanner drop folder. In this course 00_load_pdfs.sql puts four rows in.
--
-- file_bytes is kept next to the BLOB because lesson 1 compares it with the
-- length of the base64 text that goes on the wire.

create table inv_documents (
  id           number generated by default on null as identity
, filename     varchar2(255 char) not null
, media_type   varchar2(100 char) default on null 'application/pdf' not null
, file_bytes   number not null
, content      blob not null
, received_at  timestamp default on null systimestamp not null
, status       varchar2(20 char) default on null 'NEW' not null
, constraint inv_documents_pk primary key (id)
, constraint inv_documents_uk unique (filename)
, constraint inv_documents_status_ck
    check (status in ('NEW', 'EXTRACTED', 'POSTED', 'REVIEW', 'FAILED'))
);

-- ---------------------------------------------------------------------------
-- One row for each model run over one document
-- ---------------------------------------------------------------------------
-- raw_json keeps the answer as it arrived, before anything reads it. Two
-- reasons, and both come up in the course:
--   * a second posting costs nothing, because you post from this row, not from
--     a new run;
--   * when your parsing meets a value you did not plan for, the evidence is
--     still here.

-- execution_id and session_id are filled only when the run went through an
-- agent, which lesson 5 changes it to. They are the join back to the UC AI
-- trace tables, so an invoice row can always answer "which run produced me?".

create table inv_extractions (
  id                number generated by default on null as identity
, document_id       number not null
, model             varchar2(100 char) not null
, extracted_at      timestamp default on null systimestamp not null
, seconds           number(6,1)
, prompt_tokens     number
, completion_tokens number
, total_tokens      number
, execution_id      number
, session_id        varchar2(255 char)
, raw_json          clob
, error_message     varchar2(4000 char)
, constraint inv_extractions_pk primary key (id)
, constraint inv_extractions_fk foreign key (document_id)
    references inv_documents (id)
, constraint inv_extractions_json_ck check (raw_json is json)
);

create index inv_extractions_ix1 on inv_extractions (document_id);

-- ---------------------------------------------------------------------------
-- The posted invoice
-- ---------------------------------------------------------------------------
-- invoice_date_raw holds the date STRING as it is printed, next to the date the
-- model parsed. Lesson 3 needs both: "08/11/2026" is a different day in
-- Cleveland and in Leeds, and only the raw string shows what was on the page.
--
-- The unique key on (supplier_name, invoice_no) is the whole duplicate defence
-- of lesson 4. Nothing in a prompt can give you that.

create table inv_invoices (
  id                number generated by default on null as identity
, document_id       number not null
, extraction_id     number not null
, supplier_name     varchar2(200 char) not null
, invoice_no        varchar2(60 char) not null
, invoice_date      date
, invoice_date_raw  varchar2(60 char)
, po_number         varchar2(40 char)
, currency          varchar2(5 char) not null
, net_amount        number(14,2) not null
, tax_amount        number(14,2) not null
, total_amount      number(14,2) not null
, needs_review      varchar2(1 char) default on null 'N' not null
, review_reasons    varchar2(400 char)
, posted_at         timestamp default on null systimestamp not null
, constraint inv_invoices_pk primary key (id)
, constraint inv_invoices_doc_uk unique (document_id)
, constraint inv_invoices_uk unique (supplier_name, invoice_no)
, constraint inv_invoices_doc_fk foreign key (document_id)
    references inv_documents (id)
, constraint inv_invoices_extr_fk foreign key (extraction_id)
    references inv_extractions (id)
, constraint inv_invoices_review_ck check (needs_review in ('Y', 'N'))
);

-- No index on document_id: inv_invoices_doc_uk already made one.

-- ---------------------------------------------------------------------------
-- The lines of one invoice
-- ---------------------------------------------------------------------------
-- line_total has NO positive check. A discount line and a credit line are
-- negative, and the sum of the lines is what lesson 3 compares with net_amount.
--
-- seq is the order the lines arrived in. position is the number PRINTED on the
-- page, which is 10, 20, 30 on a German invoice and can be missing altogether
-- on a charge that is printed under the table.

create table inv_invoice_lines (
  id           number generated by default on null as identity
, invoice_id   number not null
, seq          number not null
, position     number
, description  varchar2(400 char)
, kind         varchar2(10 char) not null
, quantity     number(14,3)
, unit_price   number(14,4)
, line_total   number(14,2) not null
, constraint inv_invoice_lines_pk primary key (id)
, constraint inv_invoice_lines_uk unique (invoice_id, seq)
, constraint inv_invoice_lines_fk foreign key (invoice_id)
    references inv_invoices (id) on delete cascade
, constraint inv_invoice_lines_kind_ck
    check (kind in ('GOODS', 'SERVICE', 'FREIGHT', 'DISCOUNT', 'OTHER'))
);

-- No index on invoice_id alone: inv_invoice_lines_uk leads with it.

-- ---------------------------------------------------------------------------
-- What the company already ordered
-- ---------------------------------------------------------------------------
-- Two of the four documents point at a row here, one points at a purchase order
-- that does not exist, and one is not an invoice at all. This table is the
-- reason the database can refuse a document that reads perfectly well.

create table inv_purchase_orders (
  po_number      varchar2(40 char)
, supplier_name  varchar2(200 char) not null
, currency       varchar2(5 char) not null
, amount_limit   number(14,2) not null
, status         varchar2(10 char) default on null 'OPEN' not null
, constraint inv_purchase_orders_pk primary key (po_number)
, constraint inv_purchase_orders_status_ck check (status in ('OPEN', 'CLOSED'))
);

-- ---------------------------------------------------------------------------
-- Seed the purchase orders
-- ---------------------------------------------------------------------------
-- Three rows, and each one has a job in lesson 3.

-- Matches ferrotek.pdf, which is 2,136.50 net. Open, and under the limit. This
-- is the one document that must post with no review.
insert into inv_purchase_orders (po_number, supplier_name, currency, amount_limit, status)
values ('PO-4500198231', 'FerroTek Components Ltd', 'GBP', 2600.00, 'OPEN');

-- Matches nordwind.pdf, which is 6,450.85 net. That is 150.85 OVER this limit.
-- Being over the order is the most common check in accounts payable, and the
-- document itself gives you no way to see it.
insert into inv_purchase_orders (po_number, supplier_name, currency, amount_limit, status)
values ('PO-4500198247', 'Nordwind Industrietechnik GmbH', 'EUR', 6300.00, 'OPEN');

-- Matches no document. It is here so that a missing purchase order is not the
-- only way the purchase-order check can fail.
insert into inv_purchase_orders (po_number, supplier_name, currency, amount_limit, status)
values ('PO-4500197004', 'FerroTek Components Ltd', 'GBP', 900.00, 'CLOSED');

-- The purchase order on halvorsen.pdf, PO-4500199003, is missing on purpose.

commit;

-- ---------------------------------------------------------------------------
-- Report
-- ---------------------------------------------------------------------------
declare
  l_tables pls_integer;
  l_orders pls_integer;
begin
  select count(*)
    into l_tables
    from user_tables
   where table_name in ('INV_DOCUMENTS', 'INV_EXTRACTIONS', 'INV_INVOICES'
                      , 'INV_INVOICE_LINES', 'INV_PURCHASE_ORDERS');

  select count(*) into l_orders from inv_purchase_orders;

  sys.dbms_output.put_line('Demo schema in place: ' || l_tables || ' of 5 tables.');
  sys.dbms_output.put_line('Purchase orders seeded: ' || l_orders || '.');
  sys.dbms_output.put_line('Next: run 00_load_pdfs.sql, then 00_precheck.sql.');
end;
/
