-- ============================================================================
-- UC AI tutorial - "Put an Agent in APEX" - setup
-- Run this ONCE, before lesson 1.
-- ============================================================================
-- This course puts a chat region in front of the service-contract desk. The
-- desk itself is the agent built in the "Build an Agent" course.
--
-- You do NOT have to do that course first. This one script creates everything
-- the desk needs: the six tables and their data, the PL/SQL package behind the
-- tools, the four tools, the prompt profile, and the agent.
--
-- If you already did "Build an Agent", run it anyway. Every step creates what
-- is absent and updates what is there, so it changes nothing.
--
-- To remove it all again, run 00_teardown.sql from the "Build an Agent"
-- examples directory.
-- ============================================================================

-- @dblinter ignore(G-7220): the package body of the first course is inlined into
-- this one script so the reader runs a single command. Its private functions are
-- declared where they are defined, which is correct in the .pkb this came from;
-- the rule only fires because the body now sits inside a .sql file.
-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl.

set define off
set serveroutput on

prompt
prompt ==========================================================
prompt  Creating the service-contract desk...
prompt ==========================================================
prompt


-- ==== from 00_setup.sql ============================================================

-- ============================================================================
-- UC AI tutorial — "Build an Agent"
-- Demo schema: the service-contract desk
-- ============================================================================
-- Creates six tables and seeds them. Safe to run more than one time: it deletes
-- the objects first, so a second run gives the same result as the first.
--
-- Every date is relative to sysdate, so the coverage-window lessons stay correct
-- however long after publication you run this.
--
-- To remove everything again, run 00_teardown.sql.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.


-- ---------------------------------------------------------------------------
-- Delete the objects of an earlier run
-- ---------------------------------------------------------------------------
declare
  -- Child tables first, so no foreign key blocks a drop.
  c_tables constant sys.odcivarchar2list := sys.odcivarchar2list(
    'SC_CREDIT_NOTES'
  , 'SC_INVOICES'
  , 'SC_SERVICE_CALLS'
  , 'SC_ASSETS'
  , 'SC_CONTRACTS'
  , 'SC_CUSTOMERS'
  );
  e_table_missing exception;
  pragma exception_init(e_table_missing, -942);
begin
  <<table_loop>>
  for i in 1 .. c_tables.count loop
    begin
      -- @dblinter ignore(g-6010): the name comes from the constant list above, not from user input
      execute immediate 'drop table ' || c_tables(i) || ' cascade constraints purge';
    exception
      when e_table_missing then
        -- @dblinter ignore(g-5080): an absent table is the normal case on a first run
        null;
    end;
  end loop table_loop;
end;
/

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table sc_customers (
  id            number generated by default on null as identity
, name          varchar2(120 char) not null
, city          varchar2(80 char)
, constraint sc_customers_pk primary key (id)
);

-- A service contract covers one customer between two dates. The coverage level
-- decides what a credit note may cover: 'GOLD' covers parts and labour,
-- 'SILVER' covers labour only.
create table sc_contracts (
  id              number generated by default on null as identity
, customer_id     number not null
, contract_no     varchar2(20 char) not null
, coverage_level  varchar2(10 char) not null
, starts_on       date not null
, ends_on         date not null
, constraint sc_contracts_pk primary key (id)
, constraint sc_contracts_uk unique (contract_no)
, constraint sc_contracts_customer_fk foreign key (customer_id)
    references sc_customers (id)
, constraint sc_contracts_level_ck check (coverage_level in ('GOLD', 'SILVER'))
, constraint sc_contracts_dates_ck check (ends_on >= starts_on)
);

create table sc_assets (
  id           number generated by default on null as identity
, contract_id  number not null
, asset_tag    varchar2(30 char) not null
, model        varchar2(120 char)
, installed_on date
, constraint sc_assets_pk primary key (id)
, constraint sc_assets_uk unique (asset_tag)
, constraint sc_assets_contract_fk foreign key (contract_id)
    references sc_contracts (id)
);

create table sc_service_calls (
  id           number generated by default on null as identity
, contract_id  number not null
, asset_id     number not null
, called_on    date not null
, summary      varchar2(400 char)
, parts_cost   number(10, 2) default on null 0 not null
, labour_cost  number(10, 2) default on null 0 not null
, constraint sc_service_calls_pk primary key (id)
, constraint sc_service_calls_contract_fk foreign key (contract_id)
    references sc_contracts (id)
, constraint sc_service_calls_asset_fk foreign key (asset_id)
    references sc_assets (id)
);

create table sc_invoices (
  id              number generated by default on null as identity
, contract_id     number not null
, service_call_id number not null
, invoice_no      varchar2(20 char) not null
, invoiced_on     date not null
, parts_amount    number(10, 2) default on null 0 not null
, labour_amount   number(10, 2) default on null 0 not null
, constraint sc_invoices_pk primary key (id)
, constraint sc_invoices_uk unique (invoice_no)
, constraint sc_invoices_contract_fk foreign key (contract_id)
    references sc_contracts (id)
, constraint sc_invoices_call_fk foreign key (service_call_id)
    references sc_service_calls (id)
);

comment on column sc_invoices.parts_amount is 'Parts part of the invoice; a SILVER contract does not cover this';
comment on column sc_invoices.labour_amount is 'Labour part of the invoice; every coverage level covers this';

create table sc_credit_notes (
  id          number generated by default on null as identity
, invoice_id  number not null
, contract_id number not null
, credit_no   varchar2(20 char) not null
, amount      number(10, 2) not null
, reason      varchar2(400 char)
, created_at  timestamp default on null systimestamp not null
  -- Do NOT read APEX$SESSION here. Inside an agent run, UC AI creates its own
  -- synthetic APEX session, so APP_USER is 'UC_AI_AGENT_EXEC' and not the person
  -- who asked. The database user is always true. Lesson 5 explains this, and the
  -- handler records the engineer of the run context instead.
, created_by  varchar2(255 char) default on null
                sys_context('userenv', 'session_user') not null
, constraint sc_credit_notes_pk primary key (id)
, constraint sc_credit_notes_uk unique (credit_no)
, constraint sc_credit_notes_invoice_fk foreign key (invoice_id)
    references sc_invoices (id)
, constraint sc_credit_notes_contract_fk foreign key (contract_id)
    references sc_contracts (id)
, constraint sc_credit_notes_amount_ck check (amount > 0)
);

create index sc_contracts_customer_idx on sc_contracts (customer_id);
create index sc_assets_contract_idx on sc_assets (contract_id);
create index sc_service_calls_contract_idx on sc_service_calls (contract_id);
create index sc_invoices_contract_idx on sc_invoices (contract_id);
create index sc_credit_notes_invoice_idx on sc_credit_notes (invoice_id);

create sequence sc_credit_notes_no_seq start with 9002;

-- ---------------------------------------------------------------------------
-- Seed data
-- ---------------------------------------------------------------------------
-- The ids are fixed, so every lesson and every recorded run names the same rows.
--
-- Contract 88 is GOLD, contract 99 is SILVER. Together their invoices give one
-- case for each branch of the credit-note rule:
--
--   INV-1001  contract 88  inside coverage, parts + labour  -> may be credited
--   INV-1002  contract 88  BEFORE coverage starts           -> refused: out of window
--   INV-1003  contract 88  inside coverage, already credited in full -> refused
--   INV-2001  contract 99  inside coverage, parts + labour  -> parts refused (SILVER)
--                                                           -> and refused entirely
--                                                              when the run is bound
--                                                              to contract 88
-- ---------------------------------------------------------------------------

insert into sc_customers (id, name, city) values (1, 'Ferrolux Manufacturing', 'Graz');
insert into sc_customers (id, name, city) values (2, 'Northwind Foods', 'Linz');

insert into sc_contracts (id, customer_id, contract_no, coverage_level, starts_on, ends_on)
values (88, 1, 'SC-2024-088', 'GOLD', trunc(sysdate) - 365, trunc(sysdate) + 180);

insert into sc_contracts (id, customer_id, contract_no, coverage_level, starts_on, ends_on)
values (99, 2, 'SC-2024-099', 'SILVER', trunc(sysdate) - 365, trunc(sysdate) + 180);

insert into sc_assets (id, contract_id, asset_tag, model, installed_on)
values (1001, 88, 'FX-PRESS-01', 'Ferrolux HP-400 hydraulic press', trunc(sysdate) - 700);

insert into sc_assets (id, contract_id, asset_tag, model, installed_on)
values (1002, 88, 'FX-CONV-07', 'Ferrolux belt conveyor 7m', trunc(sysdate) - 500);

insert into sc_assets (id, contract_id, asset_tag, model, installed_on)
values (2001, 99, 'NW-CHILL-02', 'Northwind blast chiller 200L', trunc(sysdate) - 620);

-- inside the coverage window
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5001, 88, 1001, trunc(sysdate) - 20
      , 'Hydraulic seal replaced after pressure loss alarm', 480, 300);

-- BEFORE the coverage window starts
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5002, 88, 1002, trunc(sysdate) - 400
      , 'Belt tensioner adjusted during commissioning', 200, 150);

-- inside the window, labour only
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5003, 88, 1001, trunc(sysdate) - 10
      , 'Annual safety inspection', 0, 200);

-- inside the window, but the contract is SILVER
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5004, 99, 2001, trunc(sysdate) - 15
      , 'Compressor fan motor replaced', 600, 250);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7001, 88, 5001, 'INV-1001', trunc(sysdate) - 18, 480, 300);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7002, 88, 5002, 'INV-1002', trunc(sysdate) - 398, 200, 150);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7003, 88, 5003, 'INV-1003', trunc(sysdate) - 8, 0, 200);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7004, 99, 5004, 'INV-2001', trunc(sysdate) - 13, 600, 250);

-- INV-1003 is already credited in full, so a second credit note must be refused.
insert into sc_credit_notes (id, invoice_id, contract_id, credit_no, amount, reason)
values (9001, 7003, 88, 'CN-9001', 200, 'Inspection covered by the contract');

commit;

-- ---------------------------------------------------------------------------
-- Verification — the numbers below are what a correct setup prints
-- ---------------------------------------------------------------------------
set feedback off
prompt
prompt Setup finished. Expected: 2 customers, 2 contracts, 3 assets, 4 calls, 4 invoices, 1 credit note.
prompt

select (select count(*) from sc_customers)    as customers
     , (select count(*) from sc_contracts)    as contracts
     , (select count(*) from sc_assets)       as assets
     , (select count(*) from sc_service_calls) as calls
     , (select count(*) from sc_invoices)     as invoices
     , (select count(*) from sc_credit_notes) as credit_notes
  from dual;

prompt The four invoices, and what the credit-note rule must decide for each:
prompt

select i.invoice_no
     , c.contract_no
     , c.coverage_level
     , i.parts_amount + i.labour_amount as invoice_total
     , nvl((select sum(cn.amount) from sc_credit_notes cn where cn.invoice_id = i.id), 0) as credited
     , case
         when sc.called_on < c.starts_on or sc.called_on > c.ends_on then 'out of coverage window'
         when nvl((select sum(cn.amount) from sc_credit_notes cn where cn.invoice_id = i.id), 0)
              >= i.parts_amount + i.labour_amount                   then 'already credited in full'
         when c.coverage_level = 'SILVER' and i.parts_amount > 0     then 'labour only (SILVER)'
         else 'may be credited in full'
       end as rule_says
  from sc_invoices i
  join sc_contracts c on c.id = i.contract_id
  join sc_service_calls sc on sc.id = i.service_call_id
 order by i.invoice_no;

set feedback on

-- ==== from sc_desk_pkg.pks ============================================================

create or replace package sc_desk_pkg
  authid definer
as
  /**
  * UC AI tutorial — "Build an Agent"
  *
  * The tool handlers of the service-contract desk.
  *
  * Every function here is the target of one UC AI function tool. Each one takes
  * the tool arguments as a JSON CLOB and returns a CLOB that goes back to the
  * model.
  *
  * Two rules hold for every handler:
  *
  * 1. The contract comes from the RUN CONTEXT, never from the model. UC AI adds
  *    the run context to the arguments under the reserved key `_ctx`, after the
  *    model produced them. No tool below declares a contract parameter, so the
  *    model cannot name a contract at all.
  *
  * 2. A refusal is a RESULT, not an error. When the database declines a request,
  *    the handler returns a JSON object that says why, in a `message` the model
  *    can read out to the user and a `reason` code your own code can test. An
  *    exception could not be explained to the user.
  */

  -- The `reason` values raise_credit_note returns when it refuses. A refusal is
  -- always one of these, so a test can assert WHICH rule refused without reading
  -- the message that is meant for the model.
  subtype reason_type is varchar2(32 char);
  c_reason_no_contract      constant reason_type := 'NO_CONTRACT';
  c_reason_unknown_invoice  constant reason_type := 'UNKNOWN_INVOICE';
  c_reason_wrong_contract   constant reason_type := 'WRONG_CONTRACT';
  c_reason_out_of_window    constant reason_type := 'OUT_OF_WINDOW';
  c_reason_not_entitled     constant reason_type := 'NOT_ENTITLED';
  c_reason_already_credited constant reason_type := 'ALREADY_CREDITED';
  c_reason_amount_too_high  constant reason_type := 'AMOUNT_TOO_HIGH';
  c_reason_bad_amount       constant reason_type := 'BAD_AMOUNT';

  /*
   * Reads the contract this run is bound to out of the tool arguments.
   * Returns null when the run carries no contract.
   */
  function bound_contract_id(p_arguments in clob) return number;

  /*
   * Tool SC_GET_CONTRACT — the contract of this run, with its customer and its
   * coverage window. Takes no arguments beyond the run context.
   */
  function get_contract(p_arguments in clob) return clob;

  /*
   * Tool SC_LIST_CALLS — the service calls of this run's contract, newest first.
   * Optional argument: max_rows.
   */
  function list_calls(p_arguments in clob) return clob;

  /*
   * Tool SC_LIST_INVOICES — the invoices of this run's contract, with how much
   * of each one is already credited. Optional argument: max_rows.
   */
  function list_invoices(p_arguments in clob) return clob;

  /*
   * Tool SC_RAISE_CREDIT_NOTE — raises a credit note against one invoice.
   *
   * Arguments: invoice_no (required), amount (required), reason (optional).
   *
   * The database decides. A credit note is created only when all four hold:
   *   1. the invoice belongs to the contract bound to this run
   *   2. the service call falls inside the contract's coverage window
   *   3. the coverage level entitles the amount (GOLD covers parts and labour,
   *      SILVER covers labour only)
   *   4. the amount does not exceed what is still uncredited on that invoice
   *
   * Returns, on success:
   *   {"status":"created","credit_note":"CN-9002","amount":780,"invoice_no":"INV-1001"}
   *
   * and on a refusal:
   *   {"status":"refused","reason":"OUT_OF_WINDOW","message":"..."}
   *
   * where `reason` is one of the c_reason_* constants above. It never raises for
   * a business refusal.
   */
  function raise_credit_note(p_arguments in clob) return clob;

end sc_desk_pkg;
/

-- ==== from sc_desk_pkg.pkb ============================================================

create or replace package body sc_desk_pkg
as

  /**
  * UC AI tutorial — "Build an Agent"
  * Tool handlers of the service-contract desk. See the specification for the
  * two rules every handler follows.
  */

  -- ==========================================================================
  -- Helpers
  -- ==========================================================================

  /*
   * Builds the JSON a refusal returns. The `message` is for the model, the
   * `reason` is for your own code and for the tests.
   */
  function refusal(
    p_reason  in reason_type
  , p_message in varchar2
  ) return clob
  as
    l_result json_object_t := json_object_t();
  begin
    l_result.put('status', 'refused');
    l_result.put('reason', p_reason);
    l_result.put('message', p_message);
    return l_result.to_clob;
  end refusal;


  function bound_contract_id(p_arguments in clob) return number
  as
    l_args    json_object_t;
    l_context json_object_t;
    l_value   varchar2(4000 char);
  begin
    if p_arguments is null then
      return null;
    end if;

    l_args := json_object_t(p_arguments);

    -- UC AI always adds this key. It holds an empty object when the run carries
    -- no context, so the get_object below is safe either way.
    l_context := l_args.get_object(uc_ai.c_run_context_key);

    if l_context is null then
      return null;
    end if;

    l_value := l_context.get_string('contract_id');

    if l_value is null then
      return null;
    end if;

    return to_number(l_value);
  exception
    when value_error then
      -- A context value that is not a number is the same situation as no
      -- contract at all: the handler must refuse, not raise.
      return null;
  end bound_contract_id;


  -- ==========================================================================
  -- Read tools
  -- ==========================================================================

  function get_contract(p_arguments in clob) return clob
  as
    l_contract_id number;
    l_result      json_object_t := json_object_t();
  begin
    l_contract_id := bound_contract_id(p_arguments);

    if l_contract_id is null then
      return refusal(c_reason_no_contract
           , 'This conversation is not bound to a service contract, so I cannot read one.');
    end if;

    <<contract_row>>
    for r in (
      select c.contract_no
           , c.coverage_level
           , c.starts_on
           , c.ends_on
           , cu.name as customer_name
           , cu.city as customer_city
        from sc_contracts c
        join sc_customers cu on cu.id = c.customer_id
       where c.id = l_contract_id
    ) loop
      l_result.put('contract_no', r.contract_no);
      l_result.put('customer', r.customer_name);
      l_result.put('city', r.customer_city);
      l_result.put('coverage_level', r.coverage_level);
      l_result.put('coverage_from', to_char(r.starts_on, 'YYYY-MM-DD'));
      l_result.put('coverage_to', to_char(r.ends_on, 'YYYY-MM-DD'));
      l_result.put('covers'
        , case r.coverage_level
            when 'GOLD'   then 'parts and labour'
            when 'SILVER' then 'labour only'
          end);
    end loop contract_row;

    if l_result.get_size = 0 then
      return refusal(c_reason_no_contract, 'Contract ' || l_contract_id || ' does not exist.');
    end if;

    return l_result.to_clob;
  end get_contract;


  /*
   * Reads the optional max_rows argument, with a default and a ceiling. A model
   * may send anything, so the handler decides the real limit.
   */
  function requested_rows(p_arguments in clob) return pls_integer
  as
    c_default constant pls_integer := 20;
    c_ceiling constant pls_integer := 100;
    l_args    json_object_t;
    l_rows    number;
  begin
    if p_arguments is null then
      return c_default;
    end if;

    l_args := json_object_t(p_arguments);
    l_rows := l_args.get_number('max_rows');

    if l_rows is null or l_rows < 1 then
      return c_default;
    end if;

    return least(trunc(l_rows), c_ceiling);
  exception
    when others then
      -- @dblinter ignore(g-5040): a model can send anything for max_rows, and every bad
      -- value has the same safe answer: use the default instead of failing the run
      -- @dblinter ignore(g-5080): a rejected argument is expected input, not a fault to report
      return c_default;
  end requested_rows;


  function list_calls(p_arguments in clob) return clob
  as
    l_contract_id number;
    l_rows        pls_integer;
    l_calls       json_array_t := json_array_t();
    l_result      json_object_t := json_object_t();
  begin
    l_contract_id := bound_contract_id(p_arguments);

    if l_contract_id is null then
      return refusal(c_reason_no_contract
           , 'This conversation is not bound to a service contract, so I cannot list its calls.');
    end if;

    l_rows := requested_rows(p_arguments);

    <<call_rows>>
    for r in (
      select sc.id
           , sc.called_on
           , sc.summary
           , sc.parts_cost
           , sc.labour_cost
           , a.asset_tag
           , case
               when sc.called_on between c.starts_on and c.ends_on then 'Y'
               else 'N'
             end as in_coverage
        from sc_service_calls sc
        join sc_contracts c on c.id = sc.contract_id
        join sc_assets a on a.id = sc.asset_id
       -- The contract comes from the run context. A call of another contract can
       -- never appear here, whatever the model asked for.
       where sc.contract_id = l_contract_id
       order by sc.called_on desc
       fetch first l_rows rows only
    ) loop
      l_calls.append(
        json_object_t(
          json_object(
            'call_id'     value r.id
          , 'called_on'   value to_char(r.called_on, 'YYYY-MM-DD')
          , 'asset'       value r.asset_tag
          , 'summary'     value r.summary
          , 'parts_cost'  value r.parts_cost
          , 'labour_cost' value r.labour_cost
          , 'in_coverage' value case r.in_coverage when 'Y' then 'true' else 'false' end
          )
        )
      );
    end loop call_rows;

    l_result.put('service_calls', l_calls);
    l_result.put('count', l_calls.get_size);
    return l_result.to_clob;
  end list_calls;


  function list_invoices(p_arguments in clob) return clob
  as
    l_contract_id number;
    l_rows        pls_integer;
    l_invoices    json_array_t := json_array_t();
    l_result      json_object_t := json_object_t();
  begin
    l_contract_id := bound_contract_id(p_arguments);

    if l_contract_id is null then
      return refusal(c_reason_no_contract
           , 'This conversation is not bound to a service contract, so I cannot list its invoices.');
    end if;

    l_rows := requested_rows(p_arguments);

    <<invoice_rows>>
    for r in (
      select i.invoice_no
           , i.invoiced_on
           , i.parts_amount
           , i.labour_amount
           , i.parts_amount + i.labour_amount as total_amount
           , nvl((select sum(cn.amount)
                    from sc_credit_notes cn
                   where cn.invoice_id = i.id), 0) as credited_amount
           , case
               when sc.called_on between c.starts_on and c.ends_on then 'Y'
               else 'N'
             end as in_coverage
        from sc_invoices i
        join sc_contracts c on c.id = i.contract_id
        join sc_service_calls sc on sc.id = i.service_call_id
       where i.contract_id = l_contract_id
       order by i.invoiced_on desc
       fetch first l_rows rows only
    ) loop
      l_invoices.append(
        json_object_t(
          json_object(
            'invoice_no'        value r.invoice_no
          , 'invoiced_on'       value to_char(r.invoiced_on, 'YYYY-MM-DD')
          , 'parts_amount'      value r.parts_amount
          , 'labour_amount'     value r.labour_amount
          , 'total_amount'      value r.total_amount
          , 'credited_amount'   value r.credited_amount
          , 'uncredited_amount' value r.total_amount - r.credited_amount
          , 'in_coverage'       value case r.in_coverage when 'Y' then 'true' else 'false' end
          )
        )
      );
    end loop invoice_rows;

    l_result.put('invoices', l_invoices);
    l_result.put('count', l_invoices.get_size);
    return l_result.to_clob;
  end list_invoices;


  -- ==========================================================================
  -- Write tool
  -- ==========================================================================

  function raise_credit_note(p_arguments in clob) return clob
  as
    l_args        json_object_t;
    l_contract_id number;
    l_invoice_no  varchar2(20 char);
    l_amount      number;
    l_reason      varchar2(400 char);

    l_invoice_id     number;
    l_inv_contract   number;
    l_total          number;
    l_parts          number;
    l_labour         number;
    l_credited       number;
    l_coverage       varchar2(10 char);
    l_in_window      varchar2(1 char);
    l_credit_no      varchar2(20 char);
    l_eligible_base  number;
    l_engineer       varchar2(255 char);
    l_result         json_object_t := json_object_t();
  begin
    l_contract_id := bound_contract_id(p_arguments);

    if l_contract_id is null then
      return refusal(c_reason_no_contract
           , 'This conversation is not bound to a service contract, so I cannot raise a credit note.');
    end if;

    l_args       := json_object_t(p_arguments);
    l_invoice_no := upper(trim(l_args.get_string('invoice_no')));
    l_amount     := l_args.get_number('amount');
    l_reason      := l_args.get_string('reason');

    if l_invoice_no is null then
      return refusal(c_reason_unknown_invoice, 'Tell me which invoice number to credit.');
    end if;

    if l_amount is null or l_amount <= 0 then
      return refusal(c_reason_bad_amount, 'The credit amount must be a positive number.');
    end if;

    -- Read the invoice WITHOUT restricting to the bound contract, so a request
    -- for another contract's invoice can be refused with a clear reason instead
    -- of looking like an invoice that does not exist.
    begin
      select i.id
           , i.contract_id
           , i.parts_amount
           , i.labour_amount
           , i.parts_amount + i.labour_amount
           , nvl((select sum(cn.amount)
                    from sc_credit_notes cn
                   where cn.invoice_id = i.id), 0)
           , c.coverage_level
           , case
               when sc.called_on between c.starts_on and c.ends_on then 'Y'
               else 'N'
             end
        into l_invoice_id
           , l_inv_contract
           , l_parts
           , l_labour
           , l_total
           , l_credited
           , l_coverage
           , l_in_window
        from sc_invoices i
        join sc_contracts c on c.id = i.contract_id
        join sc_service_calls sc on sc.id = i.service_call_id
       where i.invoice_no = l_invoice_no;
    exception
      when no_data_found then
        return refusal(c_reason_unknown_invoice
             , 'There is no invoice ' || l_invoice_no || '.');
    end;

    -- Condition 1: the invoice must belong to the contract bound to this run.
    -- This is the check that makes the run context a security boundary and not
    -- only a convenience.
    if l_inv_contract != l_contract_id then
      return refusal(c_reason_wrong_contract
           , 'Invoice ' || l_invoice_no || ' belongs to another service contract, '
             || 'so it cannot be credited in this conversation.');
    end if;

    -- Condition 2: the service call must fall inside the coverage window.
    if l_in_window = 'N' then
      return refusal(c_reason_out_of_window
           , 'The service call behind invoice ' || l_invoice_no || ' is outside the '
             || 'coverage window of this contract, so the contract does not cover it.');
    end if;

    -- Condition 3: the coverage level decides what may be credited.
    -- GOLD covers parts and labour. SILVER covers labour only.
    l_eligible_base := case l_coverage
                         when 'GOLD'   then l_total
                         when 'SILVER' then l_labour
                       end;

    if l_coverage = 'SILVER' and l_amount > l_labour then
      return refusal(c_reason_not_entitled
           , 'This is a SILVER contract, which covers labour only. Invoice '
             || l_invoice_no || ' has ' || to_char(l_labour) || ' of labour and '
             || to_char(l_parts) || ' of parts, so at most ' || to_char(l_labour)
             || ' can be credited.');
    end if;

    -- Condition 4: never credit more than is still uncredited.
    if l_credited >= l_eligible_base then
      return refusal(c_reason_already_credited
           , 'Invoice ' || l_invoice_no || ' is already credited in full ('
             || to_char(l_credited) || ' of ' || to_char(l_eligible_base) || ').');
    end if;

    if l_amount > l_eligible_base - l_credited then
      return refusal(c_reason_amount_too_high
           , 'Only ' || to_char(l_eligible_base - l_credited) || ' is still uncredited on '
             || 'invoice ' || l_invoice_no || ', so ' || to_char(l_amount)
             || ' is too much.');
    end if;

    -- Every condition holds, so the credit note may be created.
    l_credit_no := 'CN-' || to_char(sc_credit_notes_no_seq.nextval);

    -- Record WHO asked, from the run context. Do not read APEX$SESSION here:
    -- inside an agent run that gives UC AI's synthetic user, not the engineer.
    -- The column default (the database user) applies when the run carries no
    -- engineer.
    l_engineer := uc_ai.run_context_value(
                    json_object_t(p_arguments).get_object(uc_ai.c_run_context_key).to_clob
                  , 'engineer');

    insert into sc_credit_notes (invoice_id, contract_id, credit_no, amount, reason, created_by)
    values (l_invoice_id, l_contract_id, l_credit_no, l_amount
          , nvl(l_reason, 'Raised by the service-contract desk agent')
          , coalesce(l_engineer, sys_context('userenv', 'session_user')));

    -- No commit here on purpose. The caller owns the transaction, so the
    -- application decides when the credit note becomes permanent. Lesson 5
    -- explains what that means when a run fails after this point.

    l_result.put('status', 'created');
    l_result.put('credit_note', l_credit_no);
    l_result.put('invoice_no', l_invoice_no);
    l_result.put('amount', l_amount);
    return l_result.to_clob;
  end raise_credit_note;

end sc_desk_pkg;
/

-- ==== from 02_profile_agent.sql ============================================================

-- ============================================================================
-- UC AI tutorial — "Build an Agent" — Lesson 2
-- The prompt profile, and the agent that uses it
-- ============================================================================
-- Moves the prompt out of your code and into a prompt profile, then creates the
-- agent that runs it.
--
-- Watch the two change_status calls at the end. Both create_prompt_profile and
-- create_agent make a DRAFT, but a call that does not name a version resolves
-- the latest ACTIVE one. Without those two calls the agent cannot be found.
-- ============================================================================
-- Repeatable: an agent cannot be deleted once it has run, because its
-- conversation history points at it. So this script deletes nothing. It creates
-- each object when it is absent, and updates it when it is already there. You
-- can run it as many times as you like, before or after the agent has run.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.


-- ---------------------------------------------------------------------------
-- 1. The prompt profile
-- ---------------------------------------------------------------------------
-- {engineer_name}, {today} and {question} are placeholders. Every placeholder in
-- either template must have a value on every call, or the run stops with an
-- error.
declare
  l_profile_id number;
  l_exists     pls_integer;
  l_profile    uc_ai_prompt_profiles%rowtype;

  c_description constant varchar2(400 char) :=
    'The service-contract desk: answers questions about one service contract and '
    || 'can raise a credit note against it.';

  c_system_prompt constant varchar2(2000 char) :=
'You are the service-contract desk of a field-service company.
You help {engineer_name}, an internal support engineer. Today is {today}.

You work on ONE service contract at a time. You cannot choose the contract: the
application decides which one this conversation is about, and your tools always
read that contract.

Rules you must follow:
- Never guess a number. Read it with a tool.
- The database decides whether a credit note is allowed. You only ask.
- When a tool refuses, explain the reason to the engineer in plain language.
- Keep answers short. The engineer is on the phone with the customer.';

  c_parameters constant varchar2(1000 char) := '{
      "type": "object",
      "properties": {
        "engineer_name": { "type": "string", "description": "Name of the support engineer" },
        "today":         { "type": "string", "description": "Todays date, as YYYY-MM-DD" },
        "question":      { "type": "string", "description": "What the engineer asked" }
      },
      "required": ["engineer_name", "today", "question"]
    }';
begin
  -- rownum stops at the first hit: this asks "is there one?", not "how many?"
  select count(*)
    into l_exists
    from uc_ai_prompt_profiles
   where code = 'SC_DESK_PROFILE'
     and version = 1
     and rownum = 1;

  if l_exists = 0 then
    l_profile_id := uc_ai_prompt_profiles_api.create_prompt_profile(
      p_code                   => 'SC_DESK_PROFILE'
    , p_description            => c_description
    , p_system_prompt_template => c_system_prompt
    , p_user_prompt_template   => '{question}'
    , p_provider               => uc_ai.c_provider_openai
    , p_model                  => uc_ai_openai.c_model_gpt_5_6_terra
    , p_parameters_schema      => c_parameters
    );
    sys.dbms_output.put_line('Prompt profile SC_DESK_PROFILE created, id=' || l_profile_id);
  else
    l_profile := uc_ai_prompt_profiles_api.get_prompt_profile('SC_DESK_PROFILE', 1);
    l_profile.description            := c_description;
    l_profile.system_prompt_template := c_system_prompt;
    l_profile.user_prompt_template   := '{question}';
    l_profile.provider               := uc_ai.c_provider_openai;
    l_profile.model                  := uc_ai_openai.c_model_gpt_5_6_terra;
    l_profile.parameters_schema      := c_parameters;
    uc_ai_prompt_profiles_api.update_prompt_profile(p_profile => l_profile);
    sys.dbms_output.put_line('Prompt profile SC_DESK_PROFILE updated.');
  end if;
end;
/

-- ---------------------------------------------------------------------------
-- 2. The agent
-- ---------------------------------------------------------------------------
declare
  l_agent_id number;
  l_exists   pls_integer;
begin
  -- rownum stops at the first hit: this asks "is there one?", not "how many?"
  select count(*)
    into l_exists
    from uc_ai_agents
   where code = 'SC_DESK'
     and version = 1
     and rownum = 1;

  if l_exists = 0 then
    l_agent_id := uc_ai_agents_api.create_agent(
      p_code                => 'SC_DESK'
    , p_description         => 'Service-contract desk agent'
    , p_agent_type          => uc_ai_agents_api.c_type_profile
    , p_prompt_profile_code => 'SC_DESK_PROFILE'
    , p_timeout_seconds     => 120
    );
    sys.dbms_output.put_line('Agent SC_DESK created, id=' || l_agent_id);
  else
    sys.dbms_output.put_line('Agent SC_DESK is already there, left as it is.');
  end if;
end;
/

-- ---------------------------------------------------------------------------
-- 3. Activate both. Do not skip this.
-- ---------------------------------------------------------------------------
-- A draft is invisible to a call that does not name a version. Miss either line
-- and the next lesson fails with "no data found" and nothing says why.
begin
  uc_ai_prompt_profiles_api.change_status(
    p_code    => 'SC_DESK_PROFILE'
  , p_version => 1
  , p_status  => uc_ai_prompt_profiles_api.c_status_active
  );

  uc_ai_agents_api.change_status(
    p_code    => 'SC_DESK'
  , p_version => 1
  , p_status  => uc_ai_agents_api.c_status_active
  );

  commit;
  sys.dbms_output.put_line('Profile and agent are both active.');
end;
/

-- ---------------------------------------------------------------------------
-- Verification — both rows must say 'active'
-- ---------------------------------------------------------------------------
set feedback off
prompt

select 'prompt profile' as object, code, version, status
  from uc_ai_prompt_profiles
 where code = 'SC_DESK_PROFILE'
union all
select 'agent', code, version, status
  from uc_ai_agents
 where code = 'SC_DESK';

set feedback on

-- ==== from 03_tools_read.sql ============================================================

-- ============================================================================
-- UC AI tutorial — "Build an Agent" — Lesson 3
-- The read tools of the service-contract desk
-- ============================================================================
-- Registers three tools that read the contract of the current run.
--
-- Look at what is NOT in these schemas: none of them has a contract parameter.
-- The contract arrives in the run context, which UC AI adds to the arguments
-- under the reserved key `_ctx` AFTER the model produced them. The model cannot
-- name a contract, so it cannot read another customer's contract.
--
-- merge_tool_from_schema is used instead of create_tool_from_schema, so you can
-- run this script again after you change a description.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.


declare
  l_tool_id number;
begin
  -- --------------------------------------------------------------------------
  -- SC_GET_CONTRACT — no arguments at all
  -- --------------------------------------------------------------------------
  l_tool_id := uc_ai_tools_api.merge_tool_from_schema(
    p_tool_code     => 'SC_GET_CONTRACT'
  , p_description   => 'Get the service contract of the current conversation: '
                    || 'the customer, the coverage level, and the coverage window. '
                    || 'Call this first when you need to know what the contract covers.'
  , p_function_call => 'return sc_desk_pkg.get_contract(:ARGUMENTS);'
  , p_json_schema   => json_object_t('{
      "type": "object",
      "properties": {},
      "required": []
    }')
  , p_tags          => apex_t_varchar2('scdesk')
  );
  sys.dbms_output.put_line('SC_GET_CONTRACT   id=' || l_tool_id);

  -- --------------------------------------------------------------------------
  -- SC_LIST_CALLS
  -- --------------------------------------------------------------------------
  l_tool_id := uc_ai_tools_api.merge_tool_from_schema(
    p_tool_code     => 'SC_LIST_CALLS'
  , p_description   => 'List the service calls of the contract of this conversation, '
                    || 'newest first. Each call says whether it falls inside the '
                    || 'coverage window of the contract.'
  , p_function_call => 'return sc_desk_pkg.list_calls(:ARGUMENTS);'
  , p_json_schema   => json_object_t('{
      "type": "object",
      "properties": {
        "max_rows": {
          "type": "integer",
          "description": "How many calls to return at most. Defaults to 20."
        }
      },
      "required": []
    }')
  , p_tags          => apex_t_varchar2('scdesk')
  );
  sys.dbms_output.put_line('SC_LIST_CALLS     id=' || l_tool_id);

  -- --------------------------------------------------------------------------
  -- SC_LIST_INVOICES
  -- --------------------------------------------------------------------------
  l_tool_id := uc_ai_tools_api.merge_tool_from_schema(
    p_tool_code     => 'SC_LIST_INVOICES'
  , p_description   => 'List the invoices of the contract of this conversation, with '
                    || 'the parts amount, the labour amount, how much is already '
                    || 'credited, and how much is still uncredited. Use this before '
                    || 'you raise a credit note.'
  , p_function_call => 'return sc_desk_pkg.list_invoices(:ARGUMENTS);'
  , p_json_schema   => json_object_t('{
      "type": "object",
      "properties": {
        "max_rows": {
          "type": "integer",
          "description": "How many invoices to return at most. Defaults to 20."
        }
      },
      "required": []
    }')
  , p_tags          => apex_t_varchar2('scdesk')
  );
  sys.dbms_output.put_line('SC_LIST_INVOICES  id=' || l_tool_id);

  commit;
end;
/

-- ---------------------------------------------------------------------------
-- Give the tools to the agent
-- ---------------------------------------------------------------------------
-- The tools reach the model through the prompt profile of the agent. The tag
-- 'scdesk' selects exactly these tools, so the agent never sees any other tool
-- in your schema.
--
-- This updates the SAME profile version lesson 2 created. It does not create a
-- new version, so the agent keeps resolving to the profile it already used.
-- get_prompt_profile returns the profile row, so the update below changes only
-- the model configuration and keeps every other value exactly as it was.
declare
  l_profile uc_ai_prompt_profiles%rowtype;
  c_config  constant clob := '{
    "g_enable_tools": true,
    "g_tool_tags": ["scdesk"],
    "g_max_tool_calls": 8
  }';
begin
  l_profile := uc_ai_prompt_profiles_api.get_prompt_profile(
                 p_code    => 'SC_DESK_PROFILE'
               , p_version => 1
               );

  l_profile.model_config_json := c_config;
  uc_ai_prompt_profiles_api.update_prompt_profile(p_profile => l_profile);

  commit;
  sys.dbms_output.put_line('Profile SC_DESK_PROFILE v1 now offers the "scdesk" tools.');
end;
/

-- ---------------------------------------------------------------------------
-- Verification — the three tools, and the proof that none takes a contract
-- ---------------------------------------------------------------------------
set feedback off
prompt
prompt The three tools, and every parameter each one declares:
prompt

select t.code
     , t.active
     , nvl(( select listagg(p.name, ', ' on overflow truncate)
                     within group (order by p.name)
               from uc_ai_tool_parameters p
              where p.tool_id = t.id )
          , '(none)') as declared_parameters
  from uc_ai_tools t
 where t.code like 'SC\_%' escape '\'
 order by t.code;

prompt
prompt No row above may name a contract. The contract comes from the run context.
prompt

set feedback on

-- ==== from 05_tool_write.sql ============================================================

-- ============================================================================
-- UC AI tutorial — "Build an Agent" — Lesson 5
-- The write tool: the model asks, the database decides
-- ============================================================================
-- Registers SC_RAISE_CREDIT_NOTE, the one tool of this agent that changes data.
--
-- The tool takes an invoice number and an amount. It does NOT take a contract:
-- the contract comes from the run context, like every read tool of lesson 3.
--
-- The four conditions of the credit-note rule live in PL/SQL, in
-- sc_desk_pkg.raise_credit_note. The model cannot skip them, argue with them, or
-- talk its way around them. It can only ask, and read the answer.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.


declare
  l_tool_id number;
begin
  l_tool_id := uc_ai_tools_api.merge_tool_from_schema(
    p_tool_code     => 'SC_RAISE_CREDIT_NOTE'
  , p_description   => 'Raise a credit note against one invoice of the contract of this '
                    || 'conversation. The database checks the contract, the coverage '
                    || 'window, the coverage level and the amount that is still '
                    || 'uncredited, and refuses with a reason when a check fails. '
                    || 'Read the invoices first, so you know the uncredited amount.'
  , p_function_call => 'return sc_desk_pkg.raise_credit_note(:ARGUMENTS);'
  , p_json_schema   => json_object_t('{
      "type": "object",
      "properties": {
        "invoice_no": {
          "type": "string",
          "description": "The invoice to credit, for example INV-1001"
        },
        "amount": {
          "type": "number",
          "description": "The amount to credit. Must not be more than the uncredited amount of the invoice."
        },
        "reason": {
          "type": "string",
          "description": "Why the credit note is raised, in one sentence"
        }
      },
      "required": ["invoice_no", "amount"]
    }')
  , p_tags          => apex_t_varchar2('scdesk')
  );

  sys.dbms_output.put_line('SC_RAISE_CREDIT_NOTE id=' || l_tool_id);
  commit;
end;
/

-- ---------------------------------------------------------------------------
-- Verification 1 — the tool still declares no contract
-- ---------------------------------------------------------------------------
set feedback off
prompt
prompt What the write tool lets the model choose:
prompt

select p.name
     , p.data_type
     , case p.required when 1 then 'yes' else 'no' end as required
  from uc_ai_tools t
  join uc_ai_tool_parameters p on p.tool_id = t.id
 where t.code = 'SC_RAISE_CREDIT_NOTE'
 order by p.required desc, p.name;

prompt
prompt There is no contract in that list, and there never can be: `_ctx` is a
prompt reserved name, so a tool that declares it is refused at registration.
prompt

-- ---------------------------------------------------------------------------
-- Verification 2 — the rule, tested without any AI
-- ---------------------------------------------------------------------------
-- Every branch of the rule is plain PL/SQL, so you can test it in a loop. This
-- is the same technique the tutorial's test suite uses: no provider call, no
-- token spent, and a result that cannot vary between runs.
prompt Each case below is decided by the database alone, with no model involved:
prompt

declare
  -- Builds what UC AI hands a tool: the model's arguments plus the `_ctx` bag.
  function args(
    p_json     in varchar2
  , p_contract in varchar2 default '88'
  ) return clob
  as
    l_args json_object_t;
  begin
    l_args := json_object_t(p_json);
    l_args.put(uc_ai.c_run_context_key
      , json_object_t('{"contract_id":"' || p_contract || '"}'));
    return l_args.to_clob;
  end args;

  procedure show(
    p_case     in varchar2
  , p_result   in clob
  )
  as
    l_result json_object_t;
  begin
    l_result := json_object_t(p_result);
    sys.dbms_output.put_line(
      rpad(p_case, 38) || ' -> ' || rpad(l_result.get_string('status'), 9)
      || coalesce(l_result.get_string('reason'), l_result.get_string('credit_note')));
  end show;
begin
  show('gold, inside window, full amount'
     , sc_desk_pkg.raise_credit_note(args('{"invoice_no":"INV-1001","amount":780}')));
  rollback;

  show('gold, one cent over the remainder'
     , sc_desk_pkg.raise_credit_note(args('{"invoice_no":"INV-1001","amount":780.01}')));

  show('call before the coverage window'
     , sc_desk_pkg.raise_credit_note(args('{"invoice_no":"INV-1002","amount":100}')));

  show('invoice already credited in full'
     , sc_desk_pkg.raise_credit_note(args('{"invoice_no":"INV-1003","amount":50}')));

  show('invoice of ANOTHER contract'
     , sc_desk_pkg.raise_credit_note(args('{"invoice_no":"INV-2001","amount":100}')));

  show('silver contract, parts included'
     , sc_desk_pkg.raise_credit_note(args('{"invoice_no":"INV-2001","amount":850}', '99')));

  show('silver contract, labour only'
     , sc_desk_pkg.raise_credit_note(args('{"invoice_no":"INV-2001","amount":250}', '99')));
  rollback;

  show('no contract bound to the run'
     , sc_desk_pkg.raise_credit_note('{"invoice_no":"INV-1001","amount":10}'));
end;
/

set feedback on

-- ---------------------------------------------------------------------------
-- Verification: everything lesson 1 needs, in one place
-- ---------------------------------------------------------------------------
declare
  l_tables  pls_integer;
  l_tools   pls_integer;
  l_agent   pls_integer;
  l_pkg     pls_integer;
begin
  select count(*) into l_tables from user_tables
   where table_name in ('SC_CUSTOMERS','SC_CONTRACTS','SC_ASSETS','SC_SERVICE_CALLS','SC_INVOICES','SC_CREDIT_NOTES');
  select count(*) into l_tools from uc_ai_tools where code like 'SC\_%' escape '\';
  -- @dblinter ignore(G-8110): the count is reported to the reader, not used as an
  -- existence test -- the line below prints "active" or "NOT ACTIVE"
  select count(*) into l_agent from uc_ai_agents where code = 'SC_DESK' and status = 'active';
  -- @dblinter ignore(G-8110): reported to the reader, see above
  select count(*) into l_pkg from user_objects
   where object_name = 'SC_DESK_PKG' and object_type = 'PACKAGE BODY' and status = 'VALID';

  sys.dbms_output.put_line('Tables      : ' || l_tables || ' of 6');
  sys.dbms_output.put_line('Package     : ' || case when l_pkg = 1 then 'valid' else 'MISSING OR INVALID' end);
  sys.dbms_output.put_line('Tools       : ' || l_tools || ' of 4');
  sys.dbms_output.put_line('Agent SC_DESK: ' || case when l_agent = 1 then 'active' else 'NOT ACTIVE' end);

  if l_tables = 6 and l_tools = 4 and l_agent = 1 and l_pkg = 1 then
    sys.dbms_output.put_line('Setup OK. Start lesson 1.');
  else
    sys.dbms_output.put_line('Setup is NOT complete. Read the lines above.');
  end if;
end;
/
