image: oven/bun:1

stages:
  - build
  - package
  - deploy

build:
  stage: build
  only:
    - main
  script:
    - echo "Building the app"
    - sh ./docs/build-static-website.sh
    - mkdir -p $CI_PROJECT_DIR/public/
    - cp -r ./docs/dist/* $CI_PROJECT_DIR/public/
  artifacts:
    paths:
      - public/
    expire_in: 1 week

package:
  stage: package
  image: debian:bullseye
  only:
    - main
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - cd public
    - zip -r ../uc-ai.zip ./*
    - cd ..
    - mkdir -p deploy
    - mv uc-ai.zip deploy/
  artifacts:
    paths:
      - deploy/uc-ai.zip
    expire_in: 1 week
  needs:
    - build

deploy_to_production:
  stage: deploy
  tags:
    - prod_web
  only:
    - main
  script:
    - echo "Deploying on webserver"
    - unzip -o deploy/uc-ai.zip -d /var/www/united-codes/products/uc-ai/docs/
    - sudo -n /bin/chown -R gitlab-deploy:gitlab-deploy /var/www/united-codes/products/uc-ai/docs/
    - sudo -n /usr/bin/find /var/www/united-codes/products/uc-ai/docs/ -type d -exec chmod 755 {} \;
    - sudo -n /usr/bin/find /var/www/united-codes/products/uc-ai/docs/ -type f -exec chmod 644 {} \;
  environment:
    name: production_webserver
    url: https://www.united-codes.com/products/uc-ai/docs
  needs:
    - package
