image: oven/bun:1

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the app"
    - sh ./docs/build-static-website.sh
    - mkdir -p $CI_PROJECT_DIR/public/
    - cp -r ./docs/dist/* $CI_PROJECT_DIR/public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
    when: always

pages:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - echo "Deploying the app"
    - zip -r ./uc-ai-docs.zip public/*
    - mv uc-ai-docs.zip public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
    when: always
  needs:
    - build
