-- ============================================================================
-- UC AI tutorial — "Give an Agent a Memory"
-- One-time setup for the whole course
-- ============================================================================
-- Creates the maintenance demo schema of a beverage plant, the two read tools
-- of the desk, its prompt profile, and the agent MX_DESK.
--
-- This course is about MEMORY, so it does not teach the agent, the profile or
-- the tools. This script builds them. If you did "Build an Agent", run this
-- anyway: it creates its own objects with the mx_ prefix and changes nothing
-- that course made.
--
-- Safe to run again. Every object is dropped and recreated, and the prompt
-- profile and the agent are updated in place.
--
-- Remove everything again with 00_teardown.sql.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.

set define off
set serveroutput on

prompt
prompt === UC AI tutorial: Give an Agent a Memory =========================
prompt

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
declare
  procedure drop_if_exists(p_table in varchar2)
  as
    l_exists pls_integer;
    l_sql    varchar2(200 char);
  begin
    select count(*) into l_exists
      from user_tables
     where table_name = p_table and rownum = 1;

    if l_exists = 1 then
      l_sql := 'drop table ' || sys.dbms_assert.simple_sql_name(p_table)
            || ' cascade constraints purge';
      execute immediate l_sql;
    end if;
  end drop_if_exists;
begin
  drop_if_exists('MX_WORK_ORDERS');
  drop_if_exists('MX_ALARMS');
  drop_if_exists('MX_TECHNICIANS');
  drop_if_exists('MX_ASSETS');
end;
/

create table mx_assets (
  asset_no     varchar2(30 char)  not null
, asset_name   varchar2(100 char) not null
, asset_type   varchar2(50 char)  not null
, line_code    varchar2(20 char)  not null
, installed_on date               not null
, status       varchar2(20 char)  default on null 'RUNNING' not null
, constraint mx_assets_pk primary key (asset_no)
, constraint mx_assets_status_ck check (status in ('RUNNING', 'STOPPED', 'RETIRED'))
);

create table mx_technicians (
  user_name varchar2(64 char)  not null
, full_name varchar2(100 char) not null
, shift     varchar2(20 char)  not null
, constraint mx_technicians_pk primary key (user_name)
, constraint mx_technicians_shift_ck check (shift in ('EARLY', 'LATE', 'NIGHT'))
);

create table mx_alarms (
  alarm_id     number generated by default on null as identity
, asset_no     varchar2(30 char)  not null
, alarm_code   varchar2(30 char)  not null
, alarm_text   varchar2(400 char) not null
, severity     varchar2(20 char)  not null
, raised_at    date               not null
, alarm_status varchar2(20 char)  default on null 'OPEN' not null
, constraint mx_alarms_pk primary key (alarm_id)
, constraint mx_alarms_asset_fk foreign key (asset_no) references mx_assets(asset_no)
, constraint mx_alarms_status_ck check (alarm_status in ('OPEN', 'CLEARED'))
, constraint mx_alarms_severity_ck check (severity in ('LOW', 'MEDIUM', 'HIGH'))
);

create table mx_work_orders (
  wo_no            varchar2(30 char)  not null
, asset_no         varchar2(30 char)  not null
, opened_on        date               not null
, closed_on        date
, symptom          varchar2(200 char) not null
, cause            varchar2(200 char)
, action_taken     varchar2(400 char)
, downtime_minutes number
, constraint mx_work_orders_pk primary key (wo_no)
, constraint mx_work_orders_asset_fk foreign key (asset_no) references mx_assets(asset_no)
);

create index mx_work_orders_asset_ix on mx_work_orders (asset_no, opened_on desc);
create index mx_alarms_asset_ix on mx_alarms (asset_no, alarm_status);

-- ---------------------------------------------------------------------------
-- Seed: six assets on one bottling line
-- ---------------------------------------------------------------------------
insert into mx_assets (asset_no, asset_name, asset_type, line_code, installed_on, status)
  select 'AS-07', 'Rotary filler',        'FILLER',     'LINE-2', date '2019-04-11', 'RUNNING' from dual
  union all select 'AS-14', 'Syrup feed pump',    'PUMP',       'LINE-2', date '2020-09-02', 'RUNNING' from dual
  union all select 'AS-22', 'Capper head',        'CAPPER',     'LINE-2', date '2021-02-18', 'RUNNING' from dual
  union all select 'AS-31', 'Plant air compressor', 'COMPRESSOR', 'LINE-2', date '2018-06-30', 'RUNNING' from dual
  union all select 'AS-40', 'Glycol chiller',     'CHILLER',    'LINE-2', date '2022-11-07', 'RUNNING' from dual
  union all select 'AS-55', 'Discharge conveyor', 'CONVEYOR',   'LINE-2', date '2017-08-21', 'RUNNING' from dual;

insert into mx_technicians (user_name, full_name, shift)
  select 'petra.k',  'Petra Kowalski', 'NIGHT' from dual
  union all select 'sam.o',    'Sam Okafor',     'EARLY' from dual
  union all select 'nadia.r',  'Nadia Rehm',     'LATE'  from dual
  union all select 'tomas.b',  'Tomas Bilek',    'NIGHT' from dual;

-- ---------------------------------------------------------------------------
-- Seed: alarms
-- ---------------------------------------------------------------------------
-- Two of these carry the story of the course.
--
--   AS-14 has a LOW-severity low-pressure alarm that really is a nuisance: it
--         trips on every clean-in-place cycle and clears itself.
--   AS-31 has a HIGH-severity low-discharge-pressure alarm that is real, open,
--         and losing air pressure for the whole line.
--
-- The two alarms have DIFFERENT codes and different assets. Nothing in the data
-- connects them. Lesson 2 shows what connects them anyway.
insert into mx_alarms (asset_no, alarm_code, alarm_text, severity, raised_at, alarm_status)
  select 'AS-14', 'PRS-LOW'
       , 'Suction pressure below setpoint for 40 seconds during clean-in-place.'
       , 'LOW', date '2026-08-20', 'OPEN' from dual
  union all select 'AS-31', 'DIS-PRS-LOW'
       , 'Discharge pressure 4.9 bar against a 6.5 bar setpoint. Line air starved.'
       , 'HIGH', date '2026-08-23', 'OPEN' from dual
  union all select 'AS-31', 'OIL-TEMP-HI'
       , 'Oil temperature 92 C, 6 C above the warning limit.'
       , 'MEDIUM', date '2026-08-24', 'OPEN' from dual
  union all select 'AS-07', 'FILL-VAR-HI'
       , 'Fill volume variation above tolerance on heads 3 and 4.'
       , 'MEDIUM', date '2026-08-22', 'OPEN' from dual
  union all select 'AS-40', 'GLY-FLOW-LOW'
       , 'Glycol flow 12 percent below setpoint.'
       , 'LOW', date '2026-08-18', 'OPEN' from dual
  union all select 'AS-22', 'TRQ-DRIFT'
       , 'Cap torque drifting low on head 2.'
       , 'LOW', date '2026-08-11', 'CLEARED' from dual;

-- ---------------------------------------------------------------------------
-- Seed: work orders
-- ---------------------------------------------------------------------------
-- AS-14 is the asset with a history that changed. Read its rows in date order:
--
--   2025      three failures, every one of them a clogged suction strainer
--   2026-06   the strainer is REPLACED with a self-cleaning unit
--   2026-07   a failure, and the cause is the shaft coupling
--   2026-08   the same again
--
-- So "the usual cause on this pump is a clogged strainer" was true for a year
-- and has been wrong since June. That is lesson 4.
insert into mx_work_orders (wo_no, asset_no, opened_on, closed_on, symptom, cause, action_taken, downtime_minutes)
  select 'WO-31007', 'AS-14', date '2025-03-14', date '2025-03-14'
       , 'Flow drops, suction pressure low'
       , 'Suction strainer clogged with label pulp'
       , 'Strainer cleaned, pump restarted.', 55 from dual
  union all select 'WO-31119', 'AS-14', date '2025-07-02', date '2025-07-02'
       , 'Flow drops, cavitation noise'
       , 'Suction strainer clogged with label pulp'
       , 'Strainer cleaned. Cleaning interval shortened to weekly.', 70 from dual
  union all select 'WO-31240', 'AS-14', date '2025-11-19', date '2025-11-20'
       , 'Pump will not hold flow'
       , 'Suction strainer clogged with label pulp'
       , 'Strainer cleaned. Raised a request for a self-cleaning strainer.', 120 from dual
  union all select 'WO-31388', 'AS-14', date '2026-06-08', date '2026-06-09'
       , 'Planned upgrade: self-cleaning suction strainer'
       , 'Modification, not a failure'
       , 'Basket strainer replaced with a self-cleaning unit, part SCS-80. '
      || 'Weekly manual cleaning is no longer required and has been removed from the plan.', 240 from dual
  union all select 'WO-31455', 'AS-14', date '2026-07-21', date '2026-07-21'
       , 'Flow drops under load, vibration at the drive end'
       , 'Shaft coupling elastomer worn'
       , 'Coupling element replaced. Alignment checked and recorded.', 95 from dual
  union all select 'WO-31502', 'AS-14', date '2026-08-14', date '2026-08-14'
       , 'Vibration at the drive end, flow unstable'
       , 'Shaft coupling elastomer worn again'
       , 'Coupling element replaced. Alignment within limits, so the wear rate is '
      || 'under review with the reliability engineer.', 110 from dual
  union all select 'WO-31460', 'AS-31', date '2026-07-28', date '2026-07-28'
       , 'Discharge pressure low, line air starved'
       , 'Inlet filter blocked'
       , 'Inlet filter replaced. Pressure back to 6.4 bar.', 60 from dual
  union all select 'WO-31509', 'AS-31', date '2026-08-16', null
       , 'Discharge pressure low again, oil temperature rising'
       , null
       , 'Investigation open. Filter is clean, so the next check is the unloader valve.', null from dual
  union all select 'WO-31401', 'AS-31', date '2026-06-14', date '2026-06-14'
       , 'Oil temperature high'
       , 'Cooler matrix fouled'
       , 'Oil cooler cleaned.', 45 from dual
  union all select 'WO-31288', 'AS-07', date '2026-01-22', date '2026-01-22'
       , 'Fill volume variation on head 3'
       , 'Filling valve seat worn'
       , 'Valve seat replaced on head 3.', 130 from dual
  union all select 'WO-31491', 'AS-07', date '2026-08-10', date '2026-08-10'
       , 'Fill volume variation on heads 3 and 4'
       , 'Filling valve seats worn'
       , 'Seats replaced on heads 3 and 4.', 180 from dual
  union all select 'WO-31333', 'AS-22', date '2026-04-09', date '2026-04-09'
       , 'Cap torque low on head 2'
       , 'Clutch spring fatigued'
       , 'Clutch spring replaced, torque recalibrated.', 75 from dual
  union all select 'WO-31470', 'AS-22', date '2026-08-03', date '2026-08-03'
       , 'Cap torque drifting on head 2'
       , 'Torque calibration drift'
       , 'Head 2 recalibrated.', 40 from dual
  union all select 'WO-31150', 'AS-40', date '2025-08-27', date '2025-08-28'
       , 'Glycol flow low'
       , 'Pump impeller eroded'
       , 'Impeller replaced.', 210 from dual
  union all select 'WO-31421', 'AS-40', date '2026-06-25', date '2026-06-25'
       , 'Glycol flow low'
       , 'Strainer partly blocked'
       , 'Strainer cleaned.', 50 from dual
  union all select 'WO-31212', 'AS-55', date '2025-10-05', date '2025-10-05'
       , 'Belt tracking off to the drive side'
       , 'Tracking roller seized'
       , 'Tracking roller replaced.', 65 from dual
  union all select 'WO-31377', 'AS-55', date '2026-05-30', date '2026-05-30'
       , 'Belt slipping under load'
       , 'Belt tension low'
       , 'Belt retensioned.', 35 from dual
  union all select 'WO-31498', 'AS-55', date '2026-08-12', date '2026-08-12'
       , 'Intermittent stop on the discharge photo-eye'
       , 'Photo-eye lens fouled with syrup'
       , 'Lens cleaned, guard refitted.', 25 from dual;

commit;

-- ---------------------------------------------------------------------------
-- The tool handlers
-- ---------------------------------------------------------------------------
prompt Compiling mx_desk_pkg ...
@@mx_desk_pkg.pks
@@mx_desk_pkg.pkb

-- ---------------------------------------------------------------------------
-- The two read tools
-- ---------------------------------------------------------------------------
-- Neither tool has an argument. The asset comes from the run context, so a
-- conversation cannot point the desk at a different machine. "Build an Agent"
-- teaches why; this course only needs it to be true.
declare
  l_tool_id number;
begin
  l_tool_id := uc_ai_tools_api.merge_tool_from_schema(
    p_tool_code     => 'MX_GET_ASSET'
  , p_description   => 'Get the asset the technician is standing in front of: its name, '
                    || 'type, production line, install date, and every alarm that is '
                    || 'currently open on it. Takes no arguments.'
  , p_function_call => 'return mx_desk_pkg.get_asset(:ARGUMENTS);'
  , p_json_schema   => json_object_t('{
      "type": "object",
      "properties": {},
      "required": []
    }')
  , p_tags          => apex_t_varchar2('mxdesk')
  );
  sys.dbms_output.put_line('MX_GET_ASSET         id=' || l_tool_id);

  l_tool_id := uc_ai_tools_api.merge_tool_from_schema(
    p_tool_code     => 'MX_LIST_WORK_ORDERS'
  , p_description   => 'List the maintenance history of that same asset, newest first: '
                    || 'the symptom that was reported, the cause that was found, the '
                    || 'action taken, and the downtime in minutes. This is the '
                    || 'maintenance record of the machine. Takes no arguments.'
  , p_function_call => 'return mx_desk_pkg.list_work_orders(:ARGUMENTS);'
  , p_json_schema   => json_object_t('{
      "type": "object",
      "properties": {},
      "required": []
    }')
  , p_tags          => apex_t_varchar2('mxdesk')
  );
  sys.dbms_output.put_line('MX_LIST_WORK_ORDERS  id=' || l_tool_id);
  commit;
end;
/

-- ---------------------------------------------------------------------------
-- The prompt profile and the agent
-- ---------------------------------------------------------------------------
-- Both create_* calls make a DRAFT, and a call that does not name a version
-- resolves the ACTIVE one. So the change_status calls at the end are not
-- optional.
declare
  l_id      number;
  l_exists  pls_integer;
  l_profile uc_ai_prompt_profiles%rowtype;

  c_system_prompt constant varchar2(2000 char) :=
'You are the maintenance desk of the Aldenbruck bottling plant, line LINE-2.
You help the technician {technician_name}, who is standing at one machine. Today is {today}.

Read the asset and its maintenance history before you answer. Be short and
practical: a technician is reading this on a tablet next to a running line.';

  c_parameters constant varchar2(1000 char) := '{
      "type": "object",
      "properties": {
        "technician_name": { "type": "string", "description": "Name of the technician on shift" },
        "today":           { "type": "string", "description": "Todays date, as YYYY-MM-DD" },
        "question":        { "type": "string", "description": "What the technician asked" }
      },
      "required": ["technician_name", "today", "question"]
    }';

  -- 12 tool calls, not 8. Memory spends calls of its own, and this course
  -- measures how many in lesson 1.
  c_model_config constant varchar2(400 char) :=
    '{"g_enable_tools": true, "g_tool_tags": ["mxdesk"], "g_max_tool_calls": 12}';
begin
  -- rownum stops at the first hit: this asks "is there one?", not "how many?"
  select count(*) into l_exists
    from uc_ai_prompt_profiles
   where code = 'MX_DESK_PROFILE' and version = 1 and rownum = 1;

  if l_exists = 0 then
    l_id := uc_ai_prompt_profiles_api.create_prompt_profile(
      p_code                   => 'MX_DESK_PROFILE'
    , p_description            => 'The maintenance desk of line LINE-2.'
    , p_system_prompt_template => c_system_prompt
    , p_user_prompt_template   => '{question}'
    , p_provider               => uc_ai.c_provider_openai
    , p_model                  => uc_ai_openai.c_model_gpt_5_6_terra
    , p_model_config_json      => c_model_config
    , p_parameters_schema      => c_parameters
    );
    sys.dbms_output.put_line('profile MX_DESK_PROFILE created, id=' || l_id);
  else
    -- Reset it, so a reader who runs this again after lesson 3 gets lesson 1's
    -- profile back and not lesson 3's.
    l_profile := uc_ai_prompt_profiles_api.get_prompt_profile('MX_DESK_PROFILE', 1);
    l_profile.description            := 'The maintenance desk of line LINE-2.';
    l_profile.system_prompt_template := c_system_prompt;
    l_profile.user_prompt_template   := '{question}';
    l_profile.provider               := uc_ai.c_provider_openai;
    l_profile.model                  := uc_ai_openai.c_model_gpt_5_6_terra;
    l_profile.model_config_json      := c_model_config;
    l_profile.parameters_schema      := c_parameters;
    uc_ai_prompt_profiles_api.update_prompt_profile(p_profile => l_profile);
    sys.dbms_output.put_line('profile MX_DESK_PROFILE reset to its lesson 1 state.');
  end if;

  select count(*) into l_exists
    from uc_ai_agents
   where code = 'MX_DESK' and version = 1 and rownum = 1;

  if l_exists = 0 then
    l_id := uc_ai_agents_api.create_agent(
      p_code                   => 'MX_DESK'
    , p_description            => 'The maintenance desk agent.'
    , p_agent_type             => uc_ai_agents_api.c_type_profile
    , p_prompt_profile_code    => 'MX_DESK_PROFILE'
    , p_prompt_profile_version => 1
    , p_timeout_seconds        => 180
    );
    sys.dbms_output.put_line('agent MX_DESK created, id=' || l_id);
  else
    sys.dbms_output.put_line('agent MX_DESK is already there, left as it is.');
  end if;
end;
/

begin
  uc_ai_prompt_profiles_api.change_status(
    p_code => 'MX_DESK_PROFILE', p_version => 1
  , p_status => uc_ai_prompt_profiles_api.c_status_active);

  uc_ai_agents_api.change_status(
    p_code => 'MX_DESK', p_version => 1
  , p_status => uc_ai_agents_api.c_status_active);

  commit;
end;
/

-- ---------------------------------------------------------------------------
-- Memory off, whatever state this schema was in
-- ---------------------------------------------------------------------------
-- Lesson 1 starts with a desk that has NO memory, and it starts that way for a
-- reader who has already been through the course once. p_drop_store also
-- removes the files, so nothing from a previous pass survives into a recording.
declare
  e_no_config exception;
  pragma exception_init(e_no_config, -20424);
begin
  uc_ai_memory.disable_for_agent(
    p_agent_code => 'MX_DESK'
  , p_drop_store => true
  );
  commit;
  sys.dbms_output.put_line('Memory of MX_DESK removed, with its files.');
exception
  when e_no_config then
    sys.dbms_output.put_line('MX_DESK has no memory yet, which is where lesson 1 starts.');
end;
/

-- ---------------------------------------------------------------------------
-- Report
-- ---------------------------------------------------------------------------
declare
  l_assets  pls_integer;
  l_orders  pls_integer;
  l_alarms  pls_integer;
  l_tools   pls_integer;
  l_agent   pls_integer;
  l_handler pls_integer;
begin
  select count(*) into l_assets from mx_assets;
  select count(*) into l_orders from mx_work_orders;
  select count(*) into l_alarms from mx_alarms;

  select count(*) into l_tools
    from uc_ai_tools
   where code in ('MX_GET_ASSET', 'MX_LIST_WORK_ORDERS');

  select count(*) into l_agent
    from uc_ai_agents
   where code = 'MX_DESK' and status = 'active';

  -- A tool row does not check that its handler exists. Check it here, or the
  -- first run fails with PLS-00201 inside a place the reader cannot see.
  select count(*) into l_handler
    from user_objects
   where object_name = 'MX_DESK_PKG'
     and object_type = 'PACKAGE BODY'
     and status = 'VALID';

  sys.dbms_output.put_line('-------------------------------------------------------');
  sys.dbms_output.put_line('Assets:         ' || l_assets  || ' (expected 6)');
  sys.dbms_output.put_line('Work orders:    ' || l_orders  || ' (expected 18)');
  sys.dbms_output.put_line('Alarms:         ' || l_alarms  || ' (expected 6)');
  sys.dbms_output.put_line('Tools:          ' || l_tools   || ' (expected 2)');
  sys.dbms_output.put_line('Handler valid:  ' || l_handler || ' (expected 1)');
  sys.dbms_output.put_line('Agent active:   ' || l_agent   || ' (expected 1)');

  if l_assets = 6 and l_orders = 18 and l_alarms = 6
     and l_tools = 2 and l_handler = 1 and l_agent = 1
  then
    sys.dbms_output.put_line('Setup OK. Next: run 00_precheck.sql.');
  else
    sys.dbms_output.put_line('Setup INCOMPLETE. Read the numbers above.');
  end if;
  sys.dbms_output.put_line('-------------------------------------------------------');
end;
/
