-- Disable referential integrity temporarily for easier data insertion
ALTER SESSION SET CONSTRAINTS = DEFERRED;

-- Drop tables if they exist (in reverse order due to foreign key constraints)
DECLARE
    procedure drop_table_if_exists(p_table_name in varchar2) is
        l_sql varchar2(1000 char);
    begin
        l_sql := 'DROP TABLE ' || sys.dbms_assert.SQL_OBJECT_NAME(p_table_name) || ' CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE l_sql;
        SYS.DBMS_OUTPUT.PUT_LINE('Dropped table: ' || p_table_name);
    exception
        when others then
            if sqlcode != -942 then -- ORA-00942: table or view does not exist
                raise;
            end if;
            SYS.DBMS_OUTPUT.PUT_LINE('Table ' || p_table_name || ' does not exist, skipping drop.');
    end;
BEGIN
    drop_table_if_exists('TT_TIME_ENTRIES');
    drop_table_if_exists('TT_PROJECTS');
    drop_table_if_exists('TT_USERS');
END;
/

-- 1. TT_USERS Table
CREATE TABLE TT_USERS (
    USER_ID        NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME     VARCHAR2(100 char) NOT NULL,
    LAST_NAME      VARCHAR2(100 char) NOT NULL,
    EMAIL          VARCHAR2(255 char) UNIQUE NOT NULL,
    HIRE_DATE      DATE DEFAULT on null SYSDATE NOT NULL,
    IS_ACTIVE      VARCHAR2(1 char) DEFAULT on null 'Y' NOT NULL,
    CONSTRAINT is_active_ck CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- 2. TT_PROJECTS Table
CREATE TABLE TT_PROJECTS (
    PROJECT_ID     NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PROJECT_NAME   VARCHAR2(255 char) NOT NULL UNIQUE,
    PROJECT_DESCRIPTION VARCHAR2(1000 char),
    START_DATE     DATE DEFAULT on null TRUNC(SYSDATE) NOT NULL,
    END_DATE       DATE,
    STATUS         VARCHAR2(50 char) DEFAULT on null 'Active' NOT NULL, -- e.g., 'Active', 'Completed', 'On Hold', 'Archived'
    CONSTRAINT project_status_ck CHECK (STATUS IN ('Active', 'Completed', 'On Hold', 'Archived'))
);

-- 3. TT_TIME_ENTRIES Table
CREATE TABLE TT_TIME_ENTRIES (
    ENTRY_ID       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID        NUMBER(6) NOT NULL,
    PROJECT_ID     NUMBER(6) NOT NULL,
    CLOCK_IN_TIME  TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    CLOCK_OUT_TIME TIMESTAMP WITH LOCAL TIME ZONE, -- Can be NULL if currently clocked in
    NOTES          VARCHAR2(500 char),
    CONSTRAINT time_entry_user_fk
        FOREIGN KEY (USER_ID)
        REFERENCES TT_USERS (USER_ID) 
        on delete cascade,
    CONSTRAINT time_entry_project_fk
        FOREIGN KEY (PROJECT_ID)
        REFERENCES TT_PROJECTS (PROJECT_ID)
        on delete cascade,
    CONSTRAINT clock_times_ck CHECK (CLOCK_OUT_TIME IS NULL OR CLOCK_OUT_TIME >= CLOCK_IN_TIME)
);


-- Insert Data

-- Define a base timestamp for the current month.
-- This will be the first day of the current month at midnight, in the local session timezone.
DECLARE
    L_BASE_TIMESTAMP TIMESTAMP WITH LOCAL TIME ZONE := TRUNC(SYSTIMESTAMP, 'MM');
BEGIN

    -- TT_USERS Data (5 users) - Hire dates will be recent years, not specifically current month
    INSERT INTO TT_USERS (FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, IS_ACTIVE)
    VALUES ('Michael', 'Scott', 'michael.scott@dundermifflin.com', ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), - (MOD(sys.DBMS_RANDOM.VALUE, 24) * 12)), 'Y'); -- Hired within last 24 years
    INSERT INTO TT_USERS (FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, IS_ACTIVE)
    VALUES ('Pam', 'Beesly', 'pam.beesly@dundermifflin.com', ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), - (MOD(sys.DBMS_RANDOM.VALUE, 20) * 12)), 'Y');
    INSERT INTO TT_USERS (FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, IS_ACTIVE)
    VALUES ('Dwight', 'Schrute', 'dwight.schrute@dundermifflin.com', ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), - (MOD(sys.DBMS_RANDOM.VALUE, 18) * 12)), 'Y');
    INSERT INTO TT_USERS (FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, IS_ACTIVE)
    VALUES ('Jim', 'Halpert', 'jim.halpert@dundermifflin.com', ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), - (MOD(sys.DBMS_RANDOM.VALUE, 15) * 12)), 'Y');
    INSERT INTO TT_USERS (FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, IS_ACTIVE)
    VALUES ('Angela', 'Martin', 'angela.martin@dundermifflin.com', ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), - (MOD(sys.DBMS_RANDOM.VALUE, 10) * 12)), 'Y');
    INSERT INTO TT_USERS (FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, IS_ACTIVE)
    VALUES ('Kevin', 'Malone', 'kevin.malone@dundermifflin.com', ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), - (MOD(sys.DBMS_RANDOM.VALUE, 5) * 12)), 'N'); -- Inactive user, more recent hire date

    -- TT_PROJECTS Data (approx. 7 TT_projects) - Start/End dates will be recent/current year
    INSERT INTO TT_PROJECTS (PROJECT_NAME, PROJECT_DESCRIPTION, START_DATE, END_DATE, STATUS)
    VALUES ('Website Redesign', 'Overhaul of corporate website, new UX/UI', TRUNC(ADD_MONTHS(SYSDATE, -3), 'MM'), TRUNC(SYSDATE, 'MM') + 20, 'Active'); -- Ends within current month
    INSERT INTO TT_PROJECTS (PROJECT_NAME, PROJECT_DESCRIPTION, START_DATE, END_DATE, STATUS)
    VALUES ('Mobile App Development', 'Building cross-platform mobile application', TRUNC(ADD_MONTHS(SYSDATE, -2), 'MM'), NULL, 'Active'); -- Ongoing
    INSERT INTO TT_PROJECTS (PROJECT_NAME, PROJECT_DESCRIPTION, START_DATE, END_DATE, STATUS)
    VALUES ('Database Migration', 'Migrating legacy database to Oracle 23ai', TRUNC(ADD_MONTHS(SYSDATE, -8), 'MM'), TRUNC(ADD_MONTHS(SYSDATE, -2), 'MM') + 15, 'Completed'); -- Completed
    INSERT INTO TT_PROJECTS (PROJECT_NAME, PROJECT_DESCRIPTION, START_DATE, END_DATE, STATUS)
    VALUES ('Internal HR System', 'Development of new internal HR management software', TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM'), NULL, 'On Hold'); -- On Hold
    INSERT INTO TT_PROJECTS (PROJECT_NAME, PROJECT_DESCRIPTION, START_DATE, END_DATE, STATUS)
    VALUES ('Marketing Campaign 2025', 'Planning and execution of 2025 marketing initiatives', TRUNC(ADD_MONTHS(SYSDATE, -5), 'MM'), TRUNC(ADD_MONTHS(SYSDATE, 6), 'MM') + 10, 'Active');
    INSERT INTO TT_PROJECTS (PROJECT_NAME, PROJECT_DESCRIPTION, START_DATE, END_DATE, STATUS)
    VALUES ('Customer Support Automation', 'Implementing AI-driven chatbot for support', TRUNC(ADD_MONTHS(SYSDATE, -0), 'MM') + 5, NULL, 'Active'); -- Started this month
    INSERT INTO TT_PROJECTS (PROJECT_NAME, PROJECT_DESCRIPTION, START_DATE, END_DATE, STATUS)
    VALUES ('Infrastructure Upgrade', 'Upgrading server hardware and network infrastructure', TRUNC(ADD_MONTHS(SYSDATE, -18), 'MM'), TRUNC(ADD_MONTHS(SYSDATE, -6), 'MM'), 'Archived');

    -- TT_TIME_ENTRIES Data (mix of open and closed entries, all in the current month)
    -- We will dynamically generate dates and times within the current month.

    -- Michael Scott
    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'michael.scott@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Website Redesign'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(5 * 24 + 9, 'HOUR'), -- 5th day of month, 09:00
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(5 * 24 + 17, 'HOUR'),
            'Daily meeting and content review.');

    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'michael.scott@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Marketing Campaign 2025'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(6 * 24 + 8.5, 'HOUR'), -- 6th day of month, 08:30
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(6 * 24 + 12.5, 'HOUR'),
            'Brainstorming new slogan ideas.');

    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'michael.scott@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Mobile App Development'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(8 * 24 + 13, 'HOUR'), -- 8th day of month, 13:00
            NULL, -- Still clocked in
            'Reviewing app UI wireframes.');

    -- Pam Beesly
    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'pam.beesly@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Website Redesign'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(7 * 24 + 9.25, 'HOUR'), -- 7th day of month, 09:15
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(7 * 24 + 17.5, 'HOUR'),
            'Assisting with graphic design elements.');

    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'pam.beesly@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Marketing Campaign 2025'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(9 * 24 + 9, 'HOUR'), -- 9th day of month, 09:00
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(9 * 24 + 17, 'HOUR'),
            'Designing campaign visuals.');

    -- Dwight Schrute
    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'dwight.schrute@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Customer Support Automation'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(10 * 24 + 8, 'HOUR'), -- 10th day of month, 08:00
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(10 * 24 + 18, 'HOUR'),
            'Testing chatbot responses and logic. Extensive!');

    -- Jim Halpert
    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'jim.halpert@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Mobile App Development'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(11 * 24 + 9.5, 'HOUR'), -- 11th day of month, 09:30
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(11 * 24 + 17, 'HOUR'),
            'Frontend development for user profiles.');

    -- Angela Martin
    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'angela.martin@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Internal HR System'),
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(12 * 24 + 9, 'HOUR'), -- 12th day of month, 09:00
            L_BASE_TIMESTAMP + NUMTODSINTERVAL(12 * 24 + 15.5, 'HOUR'),
            'Defining requirements for payroll module.');

    -- A very recent open entry for testing (just a few hours ago)
    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'pam.beesly@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Website Redesign'),
            SYSTIMESTAMP - NUMTODSINTERVAL(3, 'HOUR'), -- 3 hours ago
            NULL,
            'Reviewing latest CSS changes.');

    -- Another open entry (from yesterday, but still within current month)
    INSERT INTO TT_TIME_ENTRIES (USER_ID, PROJECT_ID, CLOCK_IN_TIME, CLOCK_OUT_TIME, NOTES)
    VALUES ((SELECT USER_ID FROM TT_USERS WHERE EMAIL = 'dwight.schrute@dundermifflin.com'), (SELECT PROJECT_ID FROM TT_PROJECTS WHERE PROJECT_NAME = 'Customer Support Automation'),
            TRUNC(SYSTIMESTAMP, 'DD') - NUMTODSINTERVAL(2, 'HOUR'), -- Yesterday, 2 hours before midnight (e.g. 22:00 if current date is 26th, then it's 24th 22:00)
            NULL,
            'Debugging chatbot integration with CRM.');

END;
/

-- Re-enable referential integrity (important!)
ALTER SESSION SET CONSTRAINTS = IMMEDIATE;

COMMIT;
