-- ============================================================================
-- UC AI tutorial — "Analyze Data at Scale"
-- Demo schema: the cold-chain analyst
-- ============================================================================
-- Creates four tables and fills them with 24 shipments and 1176 temperature
-- readings. Safe to run more than one time: it deletes the objects first, so a
-- second run gives the same result as the first.
--
-- Every value is deterministic, and every date is relative to sysdate. So the
-- numbers on the course pages stay correct however long after publication you
-- run this.
--
-- At the end the script prints the ground truth: which shipments broke the cold
-- chain, and what the claim is. Keep that block. Every lesson compares the
-- answer of the model against it.
--
-- To remove everything again, run 00_teardown.sql.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.

set define off
set serveroutput on

-- ---------------------------------------------------------------------------
-- Delete the objects of an earlier run
-- ---------------------------------------------------------------------------
declare
  -- Child tables first, so no foreign key blocks a drop.
  c_tables constant sys.odcivarchar2list := sys.odcivarchar2list(
    'CC_CLAIMS'
  , 'CC_READINGS'
  , 'CC_SHIPMENTS'
  , 'CC_LIMITS'
  );
  e_table_missing exception;
  pragma exception_init(e_table_missing, -942);
begin
  <<table_loop>>
  for i in 1 .. c_tables.count loop
    begin
      -- @dblinter ignore(g-6010): the name comes from the constant list above, not from user input
      execute immediate 'drop table ' || c_tables(i) || ' cascade constraints purge';
    exception
      when e_table_missing then
        -- @dblinter ignore(g-5080): an absent table is the normal case on a first run
        null;
    end;
  end loop table_loop;
end;
/

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- One limit row for each product class. The three columns after the temperature
-- are what turns "too warm" into a rule a program can apply:
--   sample_minutes     how many minutes one reading stands for
--   max_minutes_above  how long the load may stay above max_temp_c
--   claim_per_hour_eur what one started hour above the limit is worth
create table cc_limits (
  product_class      varchar2(10 char) not null
, max_temp_c         number(5, 1) not null
, sample_minutes     number(4) not null
, max_minutes_above  number(4) not null
, claim_per_hour_eur number(8, 2) not null
, constraint cc_limits_pk primary key (product_class)
, constraint cc_limits_class_ck check (product_class in ('FROZEN', 'CHILLED'))
);

create table cc_shipments (
  id            number generated by default on null as identity
, shipment_no   varchar2(20 char) not null
, carrier       varchar2(60 char) not null
, lane          varchar2(60 char) not null
, product_class varchar2(10 char) not null
, departed_at   date not null
, arrived_at    date not null
, constraint cc_shipments_pk primary key (id)
, constraint cc_shipments_uk unique (shipment_no)
, constraint cc_shipments_class_fk foreign key (product_class)
    references cc_limits (product_class)
, constraint cc_shipments_dates_ck check (arrived_at >= departed_at)
);

-- One row every 30 minutes for 24 hours: 49 readings for each shipment.
create table cc_readings (
  id          number generated by default on null as identity
, shipment_id number not null
, reading_ts  date not null
, temp_c      number(5, 1) not null
, constraint cc_readings_pk primary key (id)
, constraint cc_readings_shipment_fk foreign key (shipment_id)
    references cc_shipments (id)
);

create index cc_readings_shipment_ix on cc_readings (shipment_id, reading_ts);

-- Empty at the start. Lesson 5 gives the analyst one tool that writes here.
create table cc_claims (
  id           number generated by default on null as identity
, shipment_id  number not null
, minutes_over number not null
, amount_eur   number(10, 2) not null
, filed_on     date default on null sysdate not null
, filed_by     varchar2(120 char)
, note         varchar2(400 char)
, constraint cc_claims_pk primary key (id)
, constraint cc_claims_uk unique (shipment_id)
, constraint cc_claims_shipment_fk foreign key (shipment_id)
    references cc_shipments (id)
);

-- ---------------------------------------------------------------------------
-- The limits
-- ---------------------------------------------------------------------------
insert into cc_limits (product_class, max_temp_c, sample_minutes, max_minutes_above, claim_per_hour_eur)
values ('FROZEN', -15.0, 30, 60, 240);

insert into cc_limits (product_class, max_temp_c, sample_minutes, max_minutes_above, claim_per_hour_eur)
values ('CHILLED', 8.0, 30, 60, 120);

commit;

-- ---------------------------------------------------------------------------
-- 24 shipments and 1176 readings
-- ---------------------------------------------------------------------------
-- The temperature of a healthy shipment moves in a small band well below its
-- limit. Five shipments are different, and they are the whole point of the
-- course:
--
--   SHP-2047  five readings in a row above the limit  = 150 minutes  EXCURSION
--   SHP-2052  three readings in a row above the limit =  90 minutes  EXCURSION
--   SHP-2061  four in a row, then three in a row      = 210 minutes  EXCURSION
--   SHP-2044  two readings in a row above the limit   =  60 minutes  no claim
--   SHP-2058  three SINGLE readings above the limit   =  90 minutes  no claim
--
-- SHP-2044 and SHP-2058 are the two traps. Both are above the limit. Neither
-- ever stays above it for longer than the 60 minutes the limit allows. A reader
-- who eyeballs the readings counts five broken shipments. A reader who adds up
-- every minute above the limit also counts five, because SHP-2058 sums to 90.
-- Only the run-length rule gives the right answer, which is three.
declare
  c_shipments constant pls_integer := 24;
  c_readings  constant pls_integer := 48;   -- plus reading 0, so 49 in total

  c_carriers constant sys.odcivarchar2list := sys.odcivarchar2list(
    'Nordfracht', 'Baltic Reefer', 'Alpina Logistik', 'Meridian Cargo'
  );
  c_lanes constant sys.odcivarchar2list := sys.odcivarchar2list(
    'Hamburg - Milano', 'Rotterdam - Wien', 'Antwerpen - Praha', 'Gdansk - Lyon'
  );

  l_shipment_id  number;
  l_class        cc_limits.product_class%type;
  l_limit        cc_limits.max_temp_c%type;
  l_departed     date;
  l_temp         number;
  l_reading_rows pls_integer := 0;

  -- The deterministic wiggle of a healthy reading: -0.4 .. +0.4 degrees.
  function wiggle(p_shipment in pls_integer, p_reading in pls_integer) return number
  is
  begin
    return (mod(p_shipment * 7 + p_reading * 13, 9) - 4) / 10;
  end wiggle;

  -- The temperature of one reading that is deliberately above the limit. It
  -- climbs and falls again, so an excursion reads like a real one.
  function above_limit(p_limit in number, p_step in pls_integer) return number
  is
  begin
    return p_limit + 1.5 + (mod(p_step * 11, 7) / 2);
  end above_limit;

  -- Which readings of this shipment are above the limit.
  function is_excursion_reading(p_shipment in pls_integer, p_reading in pls_integer)
    return boolean
  is
  begin
    case p_shipment
      when  7 then return p_reading between 20 and 24;              -- 5 in a row
      when 12 then return p_reading between 30 and 32;              -- 3 in a row
      when 21 then return p_reading between  8 and 11
                       or p_reading between 30 and 32;              -- 4 + 3 in a row
      when  4 then return p_reading between 15 and 16;              -- 2 in a row
      when 18 then return p_reading in (10, 20, 30);                -- three singles
      else return false;
    end case;
  end is_excursion_reading;

-- @dblinter ignore(g-3210): a fixture generator writes row by row on purpose, so that
-- every value stays readable next to the rule it illustrates. 1176 rows is not a
-- performance question.
begin
  <<shipment_loop>>
  for i in 1 .. c_shipments loop
    l_class := case when mod(i, 2) = 1 then 'FROZEN' else 'CHILLED' end;

    select max_temp_c into l_limit from cc_limits where product_class = l_class;

    l_departed := trunc(sysdate) - (25 - i) + 6 / 24;

    insert into cc_shipments (shipment_no, carrier, lane, product_class, departed_at, arrived_at)
    values ( 'SHP-2' || lpad(to_char(40 + i), 3, '0')
           , c_carriers(mod(i, c_carriers.count) + 1)
           , c_lanes(mod(i * 3, c_lanes.count) + 1)
           , l_class
           , l_departed
           , l_departed + 1 )
    returning id into l_shipment_id;

    <<reading_loop>>
    for r in 0 .. c_readings loop
      if is_excursion_reading(i, r) then
        l_temp := above_limit(l_limit, r);
      else
        l_temp := case l_class when 'FROZEN' then -20 else 4 end + wiggle(i, r);
      end if;

      insert into cc_readings (shipment_id, reading_ts, temp_c)
      values (l_shipment_id, l_departed + r * 30 / 1440, round(l_temp, 1));

      l_reading_rows := l_reading_rows + 1;
    end loop reading_loop;
  end loop shipment_loop;

  commit;

  sys.dbms_output.put_line('Shipments: ' || c_shipments || '. Readings: ' || l_reading_rows || '.');
end;
/

-- ---------------------------------------------------------------------------
-- The ground truth
-- ---------------------------------------------------------------------------
-- This is the answer the model has to reach. It is computed here in SQL, one
-- time, so that every lesson can compare against a number the database owns.
--
-- The window function pair below is the run-length rule: mark every reading
-- above the limit, group the consecutive ones with the classic "row_number
-- difference" trick, then keep only the groups that last longer than the limit
-- allows.
set feedback off

prompt
prompt ==========================================================
prompt  GROUND TRUTH - keep this. Every lesson compares to it.
prompt ==========================================================
prompt

with flagged as (
  select r.shipment_id
       , s.shipment_no
       , l.sample_minutes
       , l.max_minutes_above
       , l.claim_per_hour_eur
       , r.reading_ts
       , r.temp_c
       , row_number() over (partition by r.shipment_id order by r.reading_ts)
         - row_number() over (partition by r.shipment_id, case when r.temp_c > l.max_temp_c then 1 else 0 end
                              order by r.reading_ts) as run_key
       , case when r.temp_c > l.max_temp_c then 1 else 0 end as is_above
    from cc_readings r
    join cc_shipments s on s.id = r.shipment_id
    join cc_limits    l on l.product_class = s.product_class
), runs as (
  select shipment_no
       , max_minutes_above
       , claim_per_hour_eur
       , count(*) * min(sample_minutes) as run_minutes
       , max(temp_c) as peak_temp_c
    from flagged
   where is_above = 1
   group by shipment_id, shipment_no, max_minutes_above, claim_per_hour_eur, run_key
)
select shipment_no
     , sum(run_minutes) as minutes_over
     , max(peak_temp_c) as peak_temp_c
     , ceil(sum(run_minutes) / 60) * max(claim_per_hour_eur) as claim_eur
  from runs
 where run_minutes > max_minutes_above
 group by shipment_no
 order by shipment_no;

prompt
prompt  Shipments that were above the limit but did NOT break the cold chain:
prompt

with flagged as (
  select r.shipment_id
       , s.shipment_no
       , l.sample_minutes
       , l.max_minutes_above
       , r.reading_ts
       , row_number() over (partition by r.shipment_id order by r.reading_ts)
         - row_number() over (partition by r.shipment_id, case when r.temp_c > l.max_temp_c then 1 else 0 end
                              order by r.reading_ts) as run_key
       , case when r.temp_c > l.max_temp_c then 1 else 0 end as is_above
    from cc_readings r
    join cc_shipments s on s.id = r.shipment_id
    join cc_limits    l on l.product_class = s.product_class
), runs as (
  select shipment_no
       , max_minutes_above
       , count(*) * min(sample_minutes) as run_minutes
    from flagged
   where is_above = 1
   group by shipment_id, shipment_no, max_minutes_above, run_key
)
select shipment_no
     , sum(run_minutes)  as minutes_above_in_total
     , max(run_minutes)  as longest_run_minutes
  from runs
 group by shipment_no, max_minutes_above
having max(run_minutes) <= max(max_minutes_above)
 order by shipment_no;

set feedback on
