create or replace package body uc_ai_utils
as

  /**
  * UC AI
  * PL/SQL SDK to integrate AI capabilities into Oracle databases.
  *
  * Licensed under the GNU Lesser General Public License v3.0
  * Copyright (c) 2025-present United Codes
  * https://www.united-codes.com
  */

  -- !! This file is auto-generated by scripts/generate_uc_ai_utils_body.sh !!
  -- !! Do not edit manually - run the script to regenerate.                 !!

  c_chat      constant varchar2(16 char) := 'chat';
  c_embedding constant varchar2(16 char) := 'embedding';

  function get_providers
    return t_provider_tab pipelined
  is
    l_rec r_provider_type;
  begin
    l_rec.provider_name := 'OpenAI'; l_rec.provider_id := uc_ai.c_provider_openai; pipe row (l_rec);
    l_rec.provider_name := 'Anthropic'; l_rec.provider_id := uc_ai.c_provider_anthropic; pipe row (l_rec);
    l_rec.provider_name := 'Google'; l_rec.provider_id := uc_ai.c_provider_google; pipe row (l_rec);
    l_rec.provider_name := 'Ollama'; l_rec.provider_id := uc_ai.c_provider_ollama; pipe row (l_rec);
    l_rec.provider_name := 'OCI'; l_rec.provider_id := uc_ai.c_provider_oci; pipe row (l_rec);
    l_rec.provider_name := 'xAI'; l_rec.provider_id := uc_ai.c_provider_xai; pipe row (l_rec);
    l_rec.provider_name := 'OpenRouter'; l_rec.provider_id := uc_ai.c_provider_openrouter; pipe row (l_rec);
    return;
  end get_providers;

  function get_models (
    p_provider in varchar2 default null
  ) return t_model_tab pipelined
  is
    l_rec r_model_type;
  begin
    -- OpenAI
    if p_provider is null or p_provider = uc_ai.c_provider_openai then
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_5_1; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_5; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_5_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_5_nano; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_5_pro; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4_5; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4_1; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4_1_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4_1_nano; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4o; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4o_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o1; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o1_pro; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o1_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o3; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o3_pro; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o3_deep_research; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o3_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o4_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_o4_mini_deep_research; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_chatgpt_4o; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4_turbo; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_4_32k; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_gpt_3_5_turbo; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_text_embedding_3_small; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_text_embedding_3_large; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'openai'; l_rec.model_id := uc_ai_openai.c_model_text_embedding_ada_002; l_rec.model_type := c_embedding; pipe row (l_rec);
    end if;

    -- Anthropic
    if p_provider is null or p_provider = uc_ai.c_provider_anthropic then
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_4_5_opus; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_4_5_sonnet; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_4_5_haiku; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_4_1_opus; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_4_sonnet; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_3_7_sonnet; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_3_5_sonnet; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_3_5_haiku; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_4_opus; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'anthropic'; l_rec.model_id := uc_ai_anthropic.c_model_claude_3_opus; l_rec.model_type := c_chat; pipe row (l_rec);
    end if;

    -- Google
    if p_provider is null or p_provider = uc_ai.c_provider_google then
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_3_pro; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_2_5_pro; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_2_5_flash; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_2_5_flash_lite; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_2_0_flash; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_2_0_flash_lite; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_1_5_flash; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_1_5_flash_8b; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_1_5_pro; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'google'; l_rec.model_id := uc_ai_google.c_model_gemini_embedding_001; l_rec.model_type := c_embedding; pipe row (l_rec);
    end if;

    -- OCI
    if p_provider is null or p_provider = uc_ai.c_provider_oci then
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_4_maverick; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_4_scout; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_3_3_70b; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_3_2_90b_vision; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_3_2_11b_vision; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_3_1_405b; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_3_1_70b; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_llama_3_70b; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_command_a_03_2025; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_command_r_plus; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_command_r; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_grok_4; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_grok_3; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_grok_3_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_grok_3_fast; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_grok_3_mini_fast; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_gpt_oss_120b; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_gpt_oss_20b; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_oracle_genai; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_4; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_english_image_3; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_english_light_image_3; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_multi_image_light_3; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_multilingual_light_image_3; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_english_3; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_english_light_3; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_multi_3; l_rec.model_type := c_embedding; pipe row (l_rec);
      l_rec.provider := 'oci'; l_rec.model_id := uc_ai_oci.c_model_cohere_embed_multi_light_3; l_rec.model_type := c_embedding; pipe row (l_rec);
    end if;

    -- xAI
    if p_provider is null or p_provider = uc_ai.c_provider_xai then
      l_rec.provider := 'xai'; l_rec.model_id := uc_ai_xai.c_model_grok_4_1_fast; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'xai'; l_rec.model_id := uc_ai_xai.c_model_grok_4_fast; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'xai'; l_rec.model_id := uc_ai_xai.c_model_grok_4; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'xai'; l_rec.model_id := uc_ai_xai.c_model_grok_3_mini; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'xai'; l_rec.model_id := uc_ai_xai.c_model_grok_3; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'xai'; l_rec.model_id := uc_ai_xai.c_model_grok_2_vision; l_rec.model_type := c_chat; pipe row (l_rec);
      l_rec.provider := 'xai'; l_rec.model_id := uc_ai_xai.c_model_grok_code_fast_1; l_rec.model_type := c_chat; pipe row (l_rec);
    end if;

    return;
  end get_models;

end uc_ai_utils;
/
