#!/bin/bash

# Script to generate install_ptc_sandbox_complete.sql by inlining all source files
# This creates a single self-contained SQL script with all file contents embedded.
#
# scripts/install_ptc_sandbox.sql includes the four code-mode package files with
# @@ relative paths, so it only runs from a repository checkout. Release users
# download single files, so they need this inlined variant.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the shared package utilities
source "$SCRIPT_DIR/package_utils.sh"

ROOT_DIR="$(dirname "$SCRIPT_DIR")"
TEMPLATE_FILE="${SCRIPT_DIR}/install_ptc_sandbox.sql"
OUTPUT_FILE="${ROOT_DIR}/install_ptc_sandbox_complete.sql"
SRC_DIR=$(get_src_dir "$SCRIPT_DIR")

# Validate src directory exists
if ! validate_src_dir "$SRC_DIR"; then
    exit 1
fi

if [ ! -f "$TEMPLATE_FILE" ]; then
    echo "Error: template not found at $TEMPLATE_FILE"
    exit 1
fi

# Every sandbox package must have a spec and a body, or the generated script
# would install a partial sandbox and the runner would not compile.
for sandbox_pkg in "${SANDBOX_PACKAGES[@]}"; do
    for ext in pks pkb; do
        if [ ! -f "$SRC_DIR/packages/${sandbox_pkg}.${ext}" ]; then
            echo "Error: sandbox package file not found: ${sandbox_pkg}.${ext}"
            exit 1
        fi
    done
done

echo "Generating install_ptc_sandbox_complete.sql with inlined content..."

cat > "$OUTPUT_FILE" <<'HEADER'
-- ============================================================================
-- UC AI - code-mode sandbox installer (self-contained)
-- ============================================================================
-- GENERATED FILE - do not edit.
-- Generated by scripts/generate_ptc_sandbox_script.sh from
-- scripts/install_ptc_sandbox.sql with the code-mode package sources inlined.
--
-- Use this file if you installed UC AI from a release download. If you work
-- from a repository checkout, run scripts/install_ptc_sandbox.sql instead.
-- Undo either one with scripts/uninstall_ptc_sandbox.sql.
-- ============================================================================

HEADER

inlined=0
while IFS= read -r line || [ -n "$line" ]; do
    # Resolve an @@../src/packages/<file> include into the file content itself
    if [[ "$line" =~ ^@@\.\./src/packages/(.+)$ ]]; then
        include_file="${BASH_REMATCH[1]}"
        include_path="$SRC_DIR/packages/$include_file"

        if [ ! -f "$include_path" ]; then
            echo "Error: included file not found: $include_path"
            rm -f "$OUTPUT_FILE"
            exit 1
        fi

        {
            echo ""
            echo "/* ===================================================="
            echo "   $(get_package_description "$include_file")"
            echo "   File: $include_file"
            echo "==================================================== */"
            echo ""
            cat "$include_path"
            echo ""
        } >> "$OUTPUT_FILE"

        inlined=$((inlined + 1))
        continue
    fi

    printf '%s\n' "$line" >> "$OUTPUT_FILE"
done < "$TEMPLATE_FILE"

# A leftover @@ include means the template gained an include shape this script
# does not resolve - the output would fail for a release user.
if grep -qE '^@@' "$OUTPUT_FILE"; then
    echo "Error: unresolved @@ include left in $OUTPUT_FILE:"
    grep -nE '^@@' "$OUTPUT_FILE"
    rm -f "$OUTPUT_FILE"
    exit 1
fi

expected=$(( ${#SANDBOX_PACKAGES[@]} * 2 ))
if [ "$inlined" -ne "$expected" ]; then
    echo "Error: inlined $inlined file(s), expected $expected (spec + body per sandbox package)"
    rm -f "$OUTPUT_FILE"
    exit 1
fi

echo "Done: $OUTPUT_FILE"
echo "  inlined files: $inlined"
echo "  lines:         $(wc -l < "$OUTPUT_FILE" | tr -d ' ')"
