#!/bin/bash

# Generate test/uc_ai_test_samples.pks and .pkb from test/samples/**/*.json.
#
# The JSON files are recorded provider requests and responses. The generated
# package puts them into the database, where test_uc_ai_wire compares the request
# UC AI builds against the recorded request and feeds the recorded response back
# through the mock transport. Change the JSON file, then run this script (or
# `make generate`); never edit the generated package by hand.
#
# A sample is addressed by its path below test/samples without the .json suffix,
# e.g. 'openai/chat/4-structured-output-request'.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
SAMPLES_DIR="$ROOT_DIR/test/samples"
OUT_PKS="$ROOT_DIR/test/uc_ai_test_samples.pks"
OUT_PKB="$ROOT_DIR/test/uc_ai_test_samples.pkb"

# q'~...~' quoting: a sample may not contain the closing sequence.
CLOSE="~'"
# A PL/SQL string literal holds at most 32767 bytes.
MAX_BYTES=32000

count=0

{
  cat << 'HDR'
create or replace package uc_ai_test_samples as

  -- GENERATED by scripts/generate_test_samples.sh from test/samples/**/*.json.
  -- Do not edit: change the JSON file and run the script (or `make generate`).
  --
  -- Recorded provider requests and responses. p_name is the path below
  -- test/samples without the .json suffix, e.g.
  -- 'openai/chat/4-structured-output-request'. An unknown name raises -20990.

  function get(p_name in varchar2) return clob;

  function get_json(p_name in varchar2) return json_object_t;

end uc_ai_test_samples;
/
HDR
} > "$OUT_PKS"

{
  cat << 'HDR'
-- one recorded response contains a literal '&'; keep SQLcl from treating it as a substitution variable
set define off

create or replace package body uc_ai_test_samples as
  -- @dblinter ignore(g-7210): generated fixture package, one literal per recorded sample; its length is the data

  -- GENERATED by scripts/generate_test_samples.sh from test/samples/**/*.json.
  -- Do not edit: change the JSON file and run the script (or `make generate`).

  function get(p_name in varchar2) return clob
  as
  begin
    case p_name
HDR

  while IFS= read -r file; do
    rel="${file#"$SAMPLES_DIR"/}"
    name="${rel%.json}"

    if grep -qF -- "$CLOSE" "$file"; then
      echo "ERROR: $rel contains the literal terminator ${CLOSE}; pick another delimiter in $0" >&2
      exit 1
    fi

    size=$(wc -c < "$file" | tr -d ' ')
    if [ "$size" -gt "$MAX_BYTES" ]; then
      echo "ERROR: $rel is $size bytes; a PL/SQL literal holds at most $MAX_BYTES. Split the sample." >&2
      exit 1
    fi

    printf "      when '%s' then\n        return q'~" "$name"
    cat "$file"
    printf "~';\n\n"
    count=$((count + 1))
  done < <(find "$SAMPLES_DIR" -type f -name '*.json' | LC_ALL=C sort)

  cat << 'FTR'
      else
        raise_application_error(-20990, 'uc_ai_test_samples: unknown sample "' || p_name || '"');
    end case;
  end get;


  function get_json(p_name in varchar2) return json_object_t
  as
  begin
    return json_object_t.parse(get(p_name));
  end get_json;

end uc_ai_test_samples;
/
FTR
} > "$OUT_PKB"

echo "Generated $OUT_PKS and $OUT_PKB from $count samples."
