#!/bin/bash

# Generates uc_ai_utils.pkb by scanning uc_ai.pks for provider constants
# and provider package specs for model constants.
# This ensures the utils body stays in sync with definitions automatically.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$(dirname "$SCRIPT_DIR")/src"
OUTPUT_FILE="$SRC_DIR/packages/uc_ai_utils.pkb"
CORE_SPEC="$SRC_DIR/packages/uc_ai.pks"

# Display name overrides for providers (lowercase id -> display name)
provider_display_name() {
  case "$1" in
    openai)     echo "OpenAI" ;;
    anthropic)  echo "Anthropic" ;;
    google)     echo "Google" ;;
    ollama)     echo "Ollama" ;;
    oci)        echo "OCI" ;;
    xai)        echo "xAI" ;;
    openrouter) echo "OpenRouter" ;;
    *)          echo "$1" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}' ;;
  esac
}

# Determine model type from constant name
get_model_type() {
  if echo "$1" | grep -qi 'embed'; then
    echo "c_embedding"
  else
    echo "c_chat"
  fi
}

# Extract all c_model_* constant names from a provider spec file
get_model_constants() {
  grep -oE 'c_model_[a-z0-9_]+' "$1" | grep -v '^c_model_type$' | head -100
}

# Extract provider IDs from uc_ai.pks (e.g. "openai", "anthropic", ...)
# Skips c_provider_responses_api as it's not a real provider
get_provider_ids() {
  grep -oE "c_provider_[a-z_]+" "$CORE_SPEC" \
    | grep -v 'c_provider_responses_api' \
    | sed 's/c_provider_//' \
    | awk '!seen[$0]++'
}

echo "Generating $OUTPUT_FILE from provider specs..."

# -- Write header --
cat > "$OUTPUT_FILE" << 'HEADER'
create or replace package body uc_ai_utils
as

  /**
  * UC AI
  * PL/SQL SDK to integrate AI capabilities into Oracle databases.
  *
  * Licensed under the GNU Lesser General Public License v3.0
  * Copyright (c) 2025-present United Codes
  * https://www.united-codes.com
  */

  -- !! This file is auto-generated by scripts/generate_uc_ai_utils_body.sh !!
  -- !! Do not edit manually - run the script to regenerate.                 !!

  c_chat      constant varchar2(16 char) := 'chat';
  c_embedding constant varchar2(16 char) := 'embedding';

  function get_providers
    return t_provider_tab pipelined
  is
    l_rec r_provider_type;
  begin
HEADER

# -- Generate provider rows from uc_ai.pks constants --
while IFS= read -r provider_id; do
  disp=$(provider_display_name "$provider_id")
  echo "    l_rec.provider_name := '${disp}'; l_rec.provider_id := uc_ai.c_provider_${provider_id}; pipe row (l_rec);" >> "$OUTPUT_FILE"
done < <(get_provider_ids)

cat >> "$OUTPUT_FILE" << 'MID'
    return;
  end get_providers;

  function get_models (
    p_provider in varchar2 default null
  ) return t_model_tab pipelined
  is
    l_rec r_model_type;
  begin
MID

# -- Generate model rows from each provider spec --
while IFS= read -r provider_id; do
  pkg_name="uc_ai_${provider_id}"
  spec_file="$SRC_DIR/packages/${pkg_name}.pks"
  disp=$(provider_display_name "$provider_id")

  # Skip providers without a dedicated package or without model constants
  if [ ! -f "$spec_file" ]; then
    continue
  fi

  model_count=$(get_model_constants "$spec_file" | wc -l | tr -d ' ')
  if [ "$model_count" -eq 0 ]; then
    continue
  fi

  cat >> "$OUTPUT_FILE" << EOF
    -- ${disp}
    if p_provider is null or p_provider = uc_ai.c_provider_${provider_id} then
EOF

  while IFS= read -r const_name; do
    model_type=$(get_model_type "$const_name")
    echo "      l_rec.provider := '${provider_id}'; l_rec.model_id := ${pkg_name}.${const_name}; l_rec.model_type := ${model_type}; pipe row (l_rec);" >> "$OUTPUT_FILE"
  done < <(get_model_constants "$spec_file")

  echo "    end if;" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
done < <(get_provider_ids)

# -- Write footer --
cat >> "$OUTPUT_FILE" << 'FOOTER'
    return;
  end get_models;

end uc_ai_utils;
/
FOOTER

echo "Generated $OUTPUT_FILE successfully!"
echo ""

# Summary
while IFS= read -r provider_id; do
  disp=$(provider_display_name "$provider_id")
  spec_file="$SRC_DIR/packages/uc_ai_${provider_id}.pks"
  if [ -f "$spec_file" ]; then
    count=$(get_model_constants "$spec_file" | wc -l | tr -d ' ')
    echo "  $disp (uc_ai_${provider_id}): $count models"
  else
    echo "  $disp: no package (dynamic models)"
  fi
done < <(get_provider_ids)
