-- ============================================================================
-- UC AI tutorial — "Build an Agent"
-- Demo schema: the service-contract desk
-- ============================================================================
-- Creates six tables and seeds them. Safe to run more than one time: it deletes
-- the objects first, so a second run gives the same result as the first.
--
-- Every date is relative to sysdate, so the coverage-window lessons stay correct
-- however long after publication you run this.
--
-- To remove everything again, run 00_teardown.sql.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.

set define off
set serveroutput on

-- ---------------------------------------------------------------------------
-- Delete the objects of an earlier run
-- ---------------------------------------------------------------------------
declare
  -- Child tables first, so no foreign key blocks a drop.
  c_tables constant sys.odcivarchar2list := sys.odcivarchar2list(
    'SC_CREDIT_NOTES'
  , 'SC_INVOICES'
  , 'SC_SERVICE_CALLS'
  , 'SC_ASSETS'
  , 'SC_CONTRACTS'
  , 'SC_CUSTOMERS'
  );
  e_table_missing exception;
  pragma exception_init(e_table_missing, -942);
begin
  <<table_loop>>
  for i in 1 .. c_tables.count loop
    begin
      -- @dblinter ignore(g-6010): the name comes from the constant list above, not from user input
      execute immediate 'drop table ' || c_tables(i) || ' cascade constraints purge';
    exception
      when e_table_missing then
        -- @dblinter ignore(g-5080): an absent table is the normal case on a first run
        null;
    end;
  end loop table_loop;
end;
/

-- The credit-note sequence is not a table, so the loop above does not reach it.
-- Without this block a second run stops with ORA-00955 on the create below.
declare
  e_sequence_missing exception;
  pragma exception_init(e_sequence_missing, -2289);
begin
  -- @dblinter ignore(g-6010): the sequence name is a fixed literal, not user input
  execute immediate 'drop sequence sc_credit_notes_no_seq';
exception
  when e_sequence_missing then
    -- @dblinter ignore(g-5080): an absent sequence is the normal case on a first run
    null;
end;
/

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table sc_customers (
  id            number generated by default on null as identity
, name          varchar2(120 char) not null
, city          varchar2(80 char)
, constraint sc_customers_pk primary key (id)
);

-- A service contract covers one customer between two dates. The coverage level
-- decides what a credit note may cover: 'GOLD' covers parts and labour,
-- 'SILVER' covers labour only.
create table sc_contracts (
  id              number generated by default on null as identity
, customer_id     number not null
, contract_no     varchar2(20 char) not null
, coverage_level  varchar2(10 char) not null
, starts_on       date not null
, ends_on         date not null
, constraint sc_contracts_pk primary key (id)
, constraint sc_contracts_uk unique (contract_no)
, constraint sc_contracts_customer_fk foreign key (customer_id)
    references sc_customers (id)
, constraint sc_contracts_level_ck check (coverage_level in ('GOLD', 'SILVER'))
, constraint sc_contracts_dates_ck check (ends_on >= starts_on)
);

create table sc_assets (
  id           number generated by default on null as identity
, contract_id  number not null
, asset_tag    varchar2(30 char) not null
, model        varchar2(120 char)
, installed_on date
, constraint sc_assets_pk primary key (id)
, constraint sc_assets_uk unique (asset_tag)
, constraint sc_assets_contract_fk foreign key (contract_id)
    references sc_contracts (id)
);

create table sc_service_calls (
  id           number generated by default on null as identity
, contract_id  number not null
, asset_id     number not null
, called_on    date not null
, summary      varchar2(400 char)
, parts_cost   number(10, 2) default on null 0 not null
, labour_cost  number(10, 2) default on null 0 not null
, constraint sc_service_calls_pk primary key (id)
, constraint sc_service_calls_contract_fk foreign key (contract_id)
    references sc_contracts (id)
, constraint sc_service_calls_asset_fk foreign key (asset_id)
    references sc_assets (id)
);

create table sc_invoices (
  id              number generated by default on null as identity
, contract_id     number not null
, service_call_id number not null
, invoice_no      varchar2(20 char) not null
, invoiced_on     date not null
, parts_amount    number(10, 2) default on null 0 not null
, labour_amount   number(10, 2) default on null 0 not null
, constraint sc_invoices_pk primary key (id)
, constraint sc_invoices_uk unique (invoice_no)
, constraint sc_invoices_contract_fk foreign key (contract_id)
    references sc_contracts (id)
, constraint sc_invoices_call_fk foreign key (service_call_id)
    references sc_service_calls (id)
);

comment on column sc_invoices.parts_amount is 'Parts part of the invoice; a SILVER contract does not cover this';
comment on column sc_invoices.labour_amount is 'Labour part of the invoice; every coverage level covers this';

create table sc_credit_notes (
  id          number generated by default on null as identity
, invoice_id  number not null
, contract_id number not null
, credit_no   varchar2(20 char) not null
, amount      number(10, 2) not null
, reason      varchar2(400 char)
, created_at  timestamp default on null systimestamp not null
  -- Do NOT read APEX$SESSION here. Inside an agent run, UC AI creates its own
  -- synthetic APEX session, so APP_USER is 'UC_AI_AGENT_EXEC' and not the person
  -- who asked. The database user is always true. Lesson 5 explains this, and the
  -- handler records the engineer of the run context instead.
, created_by  varchar2(255 char) default on null
                sys_context('userenv', 'session_user') not null
, constraint sc_credit_notes_pk primary key (id)
, constraint sc_credit_notes_uk unique (credit_no)
, constraint sc_credit_notes_invoice_fk foreign key (invoice_id)
    references sc_invoices (id)
, constraint sc_credit_notes_contract_fk foreign key (contract_id)
    references sc_contracts (id)
, constraint sc_credit_notes_amount_ck check (amount > 0)
);

create index sc_contracts_customer_idx on sc_contracts (customer_id);
create index sc_assets_contract_idx on sc_assets (contract_id);
create index sc_service_calls_contract_idx on sc_service_calls (contract_id);
create index sc_invoices_contract_idx on sc_invoices (contract_id);
create index sc_credit_notes_invoice_idx on sc_credit_notes (invoice_id);

create sequence sc_credit_notes_no_seq start with 9002;

-- ---------------------------------------------------------------------------
-- Seed data
-- ---------------------------------------------------------------------------
-- The ids are fixed, so every lesson and every recorded run names the same rows.
--
-- Contract 88 is GOLD, contract 99 is SILVER. Together their invoices give one
-- case for each branch of the credit-note rule:
--
--   INV-1001  contract 88  inside coverage, parts + labour  -> may be credited
--   INV-1002  contract 88  BEFORE coverage starts           -> refused: out of window
--   INV-1003  contract 88  inside coverage, already credited in full -> refused
--   INV-2001  contract 99  inside coverage, parts + labour  -> parts refused (SILVER)
--                                                           -> and refused entirely
--                                                              when the run is bound
--                                                              to contract 88
-- ---------------------------------------------------------------------------

insert into sc_customers (id, name, city) values (1, 'Ferrolux Manufacturing', 'Graz');
insert into sc_customers (id, name, city) values (2, 'Northwind Foods', 'Linz');

insert into sc_contracts (id, customer_id, contract_no, coverage_level, starts_on, ends_on)
values (88, 1, 'SC-2024-088', 'GOLD', trunc(sysdate) - 365, trunc(sysdate) + 180);

insert into sc_contracts (id, customer_id, contract_no, coverage_level, starts_on, ends_on)
values (99, 2, 'SC-2024-099', 'SILVER', trunc(sysdate) - 365, trunc(sysdate) + 180);

insert into sc_assets (id, contract_id, asset_tag, model, installed_on)
values (1001, 88, 'FX-PRESS-01', 'Ferrolux HP-400 hydraulic press', trunc(sysdate) - 700);

insert into sc_assets (id, contract_id, asset_tag, model, installed_on)
values (1002, 88, 'FX-CONV-07', 'Ferrolux belt conveyor 7m', trunc(sysdate) - 500);

insert into sc_assets (id, contract_id, asset_tag, model, installed_on)
values (2001, 99, 'NW-CHILL-02', 'Northwind blast chiller 200L', trunc(sysdate) - 620);

-- inside the coverage window
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5001, 88, 1001, trunc(sysdate) - 20
      , 'Hydraulic seal replaced after pressure loss alarm', 480, 300);

-- BEFORE the coverage window starts
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5002, 88, 1002, trunc(sysdate) - 400
      , 'Belt tensioner adjusted during commissioning', 200, 150);

-- inside the window, labour only
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5003, 88, 1001, trunc(sysdate) - 10
      , 'Annual safety inspection', 0, 200);

-- inside the window, but the contract is SILVER
insert into sc_service_calls (id, contract_id, asset_id, called_on, summary, parts_cost, labour_cost)
values (5004, 99, 2001, trunc(sysdate) - 15
      , 'Compressor fan motor replaced', 600, 250);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7001, 88, 5001, 'INV-1001', trunc(sysdate) - 18, 480, 300);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7002, 88, 5002, 'INV-1002', trunc(sysdate) - 398, 200, 150);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7003, 88, 5003, 'INV-1003', trunc(sysdate) - 8, 0, 200);

insert into sc_invoices (id, contract_id, service_call_id, invoice_no, invoiced_on, parts_amount, labour_amount)
values (7004, 99, 5004, 'INV-2001', trunc(sysdate) - 13, 600, 250);

-- INV-1003 is already credited in full, so a second credit note must be refused.
insert into sc_credit_notes (id, invoice_id, contract_id, credit_no, amount, reason)
values (9001, 7003, 88, 'CN-9001', 200, 'Inspection covered by the contract');

commit;

-- ---------------------------------------------------------------------------
-- Verification — the numbers below are what a correct setup prints
-- ---------------------------------------------------------------------------
set feedback off
prompt
prompt Setup finished. Expected: 2 customers, 2 contracts, 3 assets, 4 calls, 4 invoices, 1 credit note.
prompt

select (select count(*) from sc_customers)    as customers
     , (select count(*) from sc_contracts)    as contracts
     , (select count(*) from sc_assets)       as assets
     , (select count(*) from sc_service_calls) as calls
     , (select count(*) from sc_invoices)     as invoices
     , (select count(*) from sc_credit_notes) as credit_notes
  from dual;

prompt The four invoices, and what the credit-note rule must decide for each:
prompt

select i.invoice_no
     , c.contract_no
     , c.coverage_level
     , i.parts_amount + i.labour_amount as invoice_total
     , nvl((select sum(cn.amount) from sc_credit_notes cn where cn.invoice_id = i.id), 0) as credited
     , case
         when sc.called_on < c.starts_on or sc.called_on > c.ends_on then 'out of coverage window'
         when nvl((select sum(cn.amount) from sc_credit_notes cn where cn.invoice_id = i.id), 0)
              >= i.parts_amount + i.labour_amount                   then 'already credited in full'
         when c.coverage_level = 'SILVER' and i.parts_amount > 0     then 'labour only (SILVER)'
         else 'may be credited in full'
       end as rule_says
  from sc_invoices i
  join sc_contracts c on c.id = i.contract_id
  join sc_service_calls sc on sc.id = i.service_call_id
 order by i.invoice_no;

set feedback on
