-- ============================================================================
-- UC AI tutorial — "Build an Agent" — Lesson 8
-- Run the desk from a page, without making the page wait
-- ============================================================================
-- A run of this agent takes about 4 seconds, and a run that uses more tools takes
-- longer. That is too long for a page submit, so the page does not call the agent.
-- It writes a request row, and a background job answers it.
--
-- This script creates:
--   sc_ai_requests    one row for each question, with its answer and its status
--   sc_desk_job_pkg   queue_request for the page, run_request for the job
--
-- Everything here is plain PL/SQL. There is no APEX object, so you can run and
-- test the whole pattern from SQLcl before you build a page on it.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.

set define off
set serveroutput on

-- ---------------------------------------------------------------------------
-- The request table the page polls
-- ---------------------------------------------------------------------------
declare
  e_table_missing exception;
  pragma exception_init(e_table_missing, -942);
begin
  -- @dblinter ignore(g-6010): a compile-time constant statement with no user input
  execute immediate 'drop table sc_ai_requests cascade constraints purge';
exception
  when e_table_missing then
    -- @dblinter ignore(g-5080): an absent table is the normal case on a first run
    null;
end;
/

create table sc_ai_requests (
  id           number generated by default on null as identity
, contract_id  number not null
, engineer     varchar2(255 char) not null
, question     varchar2(1000 char) not null
, status       varchar2(20 char) default on null 'queued' not null
, answer       clob
, error_text   varchar2(4000 char)
, requested_at timestamp default on null systimestamp not null
, finished_at  timestamp
, constraint sc_ai_requests_pk primary key (id)
, constraint sc_ai_requests_status_ck check (status in ('queued', 'running', 'done', 'failed'))
);

comment on column sc_ai_requests.status is 'queued -> running -> done or failed. The page polls this column.';

-- ---------------------------------------------------------------------------
-- What the job runs
-- ---------------------------------------------------------------------------
create or replace package sc_desk_job_pkg
  authid definer
as
  /*
   * The page calls queue_request and gets an id at once. A scheduler job calls
   * run_request, which does the slow work and writes the answer to the row.
   */
  function queue_request(
    p_contract_id in number
  , p_engineer    in varchar2
  , p_question    in varchar2
  ) return number;

  procedure run_request(
    p_request_id in number
  );
end sc_desk_job_pkg;
/

create or replace package body sc_desk_job_pkg
as

  procedure run_request(
  p_request_id in number
)
as
  l_row    sc_ai_requests%rowtype;
  l_result json_object_t;
  l_answer clob;
  l_error  varchar2(4000 char);
begin
  select *
    into l_row
    from sc_ai_requests
   where id = p_request_id;

  update sc_ai_requests
     set status = 'running'
   where id = p_request_id;
  commit;

  l_result := uc_ai_agents_api.execute_agent(
    p_agent_code       => 'SC_DESK'
  , p_input_parameters => json_object_t(
      json_object('engineer_name' value l_row.engineer
                , 'today'         value to_char(sysdate, 'YYYY-MM-DD')
                , 'question'      value l_row.question))
  , p_session_id       => uc_ai_agents_api.generate_session_id
  , p_run_context      => json_object_t(
      json_object('contract_id' value to_char(l_row.contract_id)
                , 'engineer'    value l_row.engineer))
  );

  -- Read the JSON in PL/SQL, into a local CLOB. A JSON object method inside the
  -- UPDATE itself raises ORA-40573: invalid use of PL/SQL JSON object type.
  l_answer := l_result.get_clob('final_message');

  update sc_ai_requests
     set status      = 'done'
       , answer      = l_answer
       , finished_at = systimestamp
   where id = p_request_id;
  commit;
exception
  when others then
    -- @dblinter ignore(g-5040): every failure of a run has the same treatment here,
    -- because the page must always get a final status instead of a row stuck at running
    -- @dblinter ignore(g-5080): sqlerrm is stored on the row and shown to the engineer,
    -- which is the diagnosis this table exists to carry
    l_error := sqlerrm;

    update sc_ai_requests
       set status      = 'failed'
         , error_text  = l_error
         , finished_at = systimestamp
     where id = p_request_id;
    commit;
end run_request;


  -- Returns at once. The page stores the id and polls the row.
  function queue_request(
  p_contract_id in number
, p_engineer    in varchar2
, p_question    in varchar2
) return number
as
  l_request_id number;
begin
  insert into sc_ai_requests (contract_id, engineer, question)
  values (p_contract_id, p_engineer, p_question)
  returning id into l_request_id;

  commit;

  sys.dbms_scheduler.create_job(
    job_name   => 'SC_AI_JOB_' || l_request_id
  , job_type   => 'PLSQL_BLOCK'
  , job_action => 'begin sc_desk_job_pkg.run_request(' || l_request_id || '); end;'
  , enabled    => true
  );

  return l_request_id;
end queue_request;

end sc_desk_job_pkg;
/

-- ---------------------------------------------------------------------------
-- Verification — queue one, then poll it like the page would
-- ---------------------------------------------------------------------------
declare
  l_request_id number;
  l_status     sc_ai_requests.status%type;
  l_waited     pls_integer := 0;
begin
  l_request_id := sc_desk_job_pkg.queue_request(
    p_contract_id => 88
  , p_engineer    => 'petra.k'
  , p_question    => 'Which invoices still have an uncredited amount?'
  );
  sys.dbms_output.put_line('Queued request ' || l_request_id || ', returned at once.');

  <<poll_loop>>
  loop
    select status
      into l_status
      from sc_ai_requests
     where id = l_request_id;

    exit poll_loop when l_status in ('done', 'failed') or l_waited >= 60;

    sys.dbms_session.sleep(2);
    l_waited := l_waited + 2;
  end loop poll_loop;

  sys.dbms_output.put_line('After ' || l_waited || ' seconds the status is ' || l_status || '.');

  <<answer_rows>>
  for r in ( select substr(answer, 1, 200) as answer
                  , error_text
               from sc_ai_requests
              where id = l_request_id ) loop
    sys.dbms_output.put_line(nvl(r.answer, 'error: ' || r.error_text));
  end loop answer_rows;
end;
/
