-- ============================================================================
-- UC AI tutorial — "Build an Agent" — Lesson 9
-- A hook that can stop a tool call
-- ============================================================================
-- An execution hook is a package YOU write. UC AI calls it around every run, and
-- before every tool call. It is where a rule that has nothing to do with the
-- prompt belongs: who may act, how often, and what must be recorded.
--
-- This hook does two things:
--   before_tool_call  refuses SC_RAISE_CREDIT_NOTE outside office hours
--   after_execution   writes one audit row for each finished run
--
-- The tutorial registers the hook for THIS SESSION only, with
-- set_execution_hook. A package named UC_AI_HOOK would activate itself for every
-- agent in the schema, which is not what you want while you are learning.
-- ============================================================================

-- @dblinter ignore(g-5010): a tutorial script prints its results with dbms_output on
-- purpose, so the reader sees them directly in SQLcl. A logging framework would hide
-- the output this course asks the reader to compare against the page.

set define off
set serveroutput on

-- ---------------------------------------------------------------------------
-- An audit table of our own, next to the one UC AI keeps
-- ---------------------------------------------------------------------------
declare
  e_table_missing exception;
  pragma exception_init(e_table_missing, -942);
begin
  -- @dblinter ignore(g-6010): a compile-time constant statement with no user input
  execute immediate 'drop table sc_desk_audit cascade constraints purge';
exception
  when e_table_missing then
    -- @dblinter ignore(g-5080): an absent table is the normal case on a first run
    null;
end;
/

create table sc_desk_audit (
  id            number generated by default on null as identity
, exec_id       number not null
, status        varchar2(50 char) not null
, input_tokens  number default on null 0 not null
, output_tokens number default on null 0 not null
, recorded_at   timestamp default on null systimestamp not null
, constraint sc_desk_audit_pk primary key (id)
);

-- ---------------------------------------------------------------------------
-- The hook
-- ---------------------------------------------------------------------------
-- The three procedures below are the contract. before_execution and
-- after_execution are required. before_tool_call is optional: UC AI detects
-- whether the package has it, so a hook without it stays valid.
--
-- @dblinter ignore(g-7150): the parameter lists are the hook contract UC AI calls,
-- so every one must be declared whether or not this hook reads it. Removing an
-- unused parameter would stop the hook being recognized.
create or replace package sc_desk_hook
  authid definer
as
  procedure before_execution(
    p_agent_id    in number
  , p_agent_code  in varchar2
  , p_created_by  in varchar2
  , p_apex_app_id in number
  , p_session_id  in varchar2
  );

  procedure after_execution(
    p_exec_id       in number
  , p_status        in varchar2
  , p_input_tokens  in number
  , p_output_tokens in number
  );

  procedure before_tool_call(
    p_agent_id    in number
  , p_agent_code  in varchar2
  , p_tool_code   in varchar2
  , p_created_by  in varchar2
  , p_session_id  in varchar2
  , p_apex_app_id in number
  );
end sc_desk_hook;
/

create or replace package body sc_desk_hook
as

  -- Office hours, as a whole hour of the day. Change these to see the veto.
  c_open_hour  constant pls_integer := 8;
  c_close_hour constant pls_integer := 18;

  procedure before_execution(
    p_agent_id    in number
  , p_agent_code  in varchar2
  , p_created_by  in varchar2
  , p_apex_app_id in number
  , p_session_id  in varchar2
  )
  as
  begin
    -- Raise here to refuse a run before it spends a token. This hook allows
    -- every run and only writes a line, so you can see when it fires.
    sys.dbms_output.put_line('[hook] run of ' || p_agent_code
      || ' by ' || p_created_by || ' starts.');
  end before_execution;


  procedure after_execution(
    p_exec_id       in number
  , p_status        in varchar2
  , p_input_tokens  in number
  , p_output_tokens in number
  )
  as
    -- @dblinter ignore(g-3330): an audit row must survive a rollback of the run it describes
    pragma autonomous_transaction;
  begin
    insert into sc_desk_audit (exec_id, status, input_tokens, output_tokens)
    values (p_exec_id, p_status, p_input_tokens, p_output_tokens);

    commit;
  end after_execution;


  procedure before_tool_call(
    p_agent_id    in number
  , p_agent_code  in varchar2
  , p_tool_code   in varchar2
  , p_created_by  in varchar2
  , p_session_id  in varchar2
  , p_apex_app_id in number
  )
  as
    l_hour pls_integer;
  begin
    l_hour := to_number(to_char(systimestamp, 'HH24'));

    -- A read is allowed at any time. A write is not.
    if p_tool_code = 'SC_RAISE_CREDIT_NOTE'
       and (l_hour < c_open_hour or l_hour >= c_close_hour)
    then
      raise_application_error(-20990
        , 'A credit note can only be raised between ' || c_open_hour || ':00 and '
          || c_close_hour || ':00. The request was made at ' || l_hour || ':00.');
    end if;
  end before_tool_call;

end sc_desk_hook;
/

-- ---------------------------------------------------------------------------
-- Register it for this session only
-- ---------------------------------------------------------------------------
begin
  uc_ai_agents_api.set_execution_hook('SC_DESK_HOOK');
  sys.dbms_output.put_line('Hook SC_DESK_HOOK is registered for this session.');
end;
/

-- ---------------------------------------------------------------------------
-- Verification 1 — the veto reaches the caller
-- ---------------------------------------------------------------------------
-- The window is set to the current hour, so the write tool is refused right now.
create or replace package body sc_desk_hook
as
  -- Closed all day, so a write is always refused and you can see the veto.
  c_open_hour  constant pls_integer := 0;
  c_close_hour constant pls_integer := 0;

  procedure before_execution(
    p_agent_id    in number
  , p_agent_code  in varchar2
  , p_created_by  in varchar2
  , p_apex_app_id in number
  , p_session_id  in varchar2
  )
  as
  begin
    sys.dbms_output.put_line('[hook] run of ' || p_agent_code
      || ' by ' || p_created_by || ' starts.');
  end before_execution;

  procedure after_execution(
    p_exec_id       in number
  , p_status        in varchar2
  , p_input_tokens  in number
  , p_output_tokens in number
  )
  as
    -- @dblinter ignore(g-3330): an audit row must survive a rollback of the run it describes
    pragma autonomous_transaction;
  begin
    insert into sc_desk_audit (exec_id, status, input_tokens, output_tokens)
    values (p_exec_id, p_status, p_input_tokens, p_output_tokens);
    commit;
  end after_execution;

  procedure before_tool_call(
    p_agent_id    in number
  , p_agent_code  in varchar2
  , p_tool_code   in varchar2
  , p_created_by  in varchar2
  , p_session_id  in varchar2
  , p_apex_app_id in number
  )
  as
    l_hour pls_integer;
  begin
    l_hour := to_number(to_char(systimestamp, 'HH24'));

    if p_tool_code = 'SC_RAISE_CREDIT_NOTE'
       and (l_hour >= c_close_hour or l_hour < c_open_hour)
    then
      raise_application_error(-20990
        , 'The desk cannot raise a credit note outside office hours.');
    end if;
  end before_tool_call;
end sc_desk_hook;
/

declare
  l_result json_object_t;
begin
  l_result := uc_ai_agents_api.execute_agent(
    p_agent_code       => 'SC_DESK'
  , p_input_parameters => json_object_t(
      json_object('engineer_name' value 'Petra'
                , 'today'         value to_char(sysdate, 'YYYY-MM-DD')
                , 'question'      value 'Raise a credit note on INV-1001 for 780.'))
  , p_session_id       => uc_ai_agents_api.generate_session_id
  , p_run_context      => json_object_t('{"contract_id":"88","engineer":"petra.k"}')
  );
  sys.dbms_output.put_line('The run finished: ' || substr(l_result.get_clob('final_message'), 1, 120));
exception
  when others then
    -- @dblinter ignore(g-5040): the lesson shows the raised text itself
    -- @dblinter ignore(g-5080): the message IS the teaching point here
    sys.dbms_output.put_line('The veto stopped the run: ' || substr(sqlerrm, 1, 160));
end;
/

-- ---------------------------------------------------------------------------
-- Verification 2 — who ran what, and what it used
-- ---------------------------------------------------------------------------
set feedback off
prompt
prompt Sessions of this agent, newest first:
prompt

select s.turn_count
     , s.message_count
     , s.total_input_tokens
     , s.total_output_tokens
     , s.created_by
     , s.audience
     , nvl(s.title, '(no title)') as title
     , nvl(s.feedback_rating, '-') as rating
  from uc_ai_agent_sessions s
 where s.root_agent_id = ( select a.id from uc_ai_agents a where a.code = 'SC_DESK' )
 order by s.started_at desc
 fetch first 5 rows only;

prompt
prompt What our own hook recorded:
prompt

select exec_id
     , status
     , input_tokens
     , output_tokens
  from sc_desk_audit
 order by id desc
 fetch first 5 rows only;

set feedback on
